import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  String _currentLang = 'en';

  String get currentLang => _currentLang;

  final Map<String, Map<String, String>> translations = {
    'en': {
      //settings
      'settings_title': 'Settings',
      'set_info': 'Manage your account preferences',
      'profile_info': 'Profile Information',
      'update_details': 'Update your personal details',
      'name': 'Name',
      'email': 'Email',
      'email_cannot_change': 'Email cannot be changed',
      'language_pref': 'Language Preferences',
      'choose_language': 'Choose your language',
      'recent_language': 'Recent Language:',
      'save_changes': 'Save Changes',
      'note_language_change': 'Note:\nChanging your language will apply to all lessons.',

      //home screens
      'welcome_user': 'Welcome, {name}',
      'info_home_1': 'Overall Progress',
      'quiz_info_1': 'Quiz Performance',
      'info_home_2': 'Start your journey',
      'info_home_3': 'Begin Learning Indonesian Today',
      'info_home_4': 'Choose from 18 lessons across 3 difficulty levels.',
      'info_home_5': 'Learn essential phrases for airports, hotels, restaurants, shopping, transportation, and medical facilities.',
      'info_home_6': 'transportation, and medical facilities.',
      'button_learn': 'Start Learning',
      'info_home_7': 'Explore Indonesia',
      'info_home_8': 'Popular destination',
      'info_home_9': 'Travel Tips',
      'info_home_10': 'Emergency phrases',
      'info_home_11': 'Explore Wiki',

      // levels
      'level_info': 'Choose your level',
      'level_info_2': 'Select a difficulty level to begin your journey',
      'lvl1': 'Beginner',
      'lvl1_sub': 'Basic daily conversation',
      'lvl2': 'Intermediate',
      'lvl2_sub': 'Advanced daily conversation',
      'lvl3': 'Expert',
      'lvl3_sub': 'Complex communication',
      'lvl_button': 'Start Learning',

      //scenario
      'airport': 'Airport',
      'airport_desc': 'Learn airport phrases and tips.',
      'hotel': 'Hotel',
      'hotel_desc': 'Useful sentences for hotel stays.',
      'restaurant': 'Restaurant',
      'restaurant_desc': 'Dining phrases and vocabulary.',
      'shopping': 'Shopping',
      'shopping_desc': 'Words and tips for shopping.',
      'market': 'Market',
      'market_desc': 'Essential phrases for traditional markets.',
      'transportation': 'Transportation',
      'transportation_desc': 'Get around using transport phrases.',
      'hospital': 'Hospital',
      'hospital_desc': 'Healthcare and emergency phrases.',
      'clinic': 'Clinic',
      'clinic_desc': 'Medical scenario and treatment phrases.',
      'start_learning': 'Start Learning',

      //wiki
      'wiki_info1': 'Indonesia Tourist Wiki',
      'wiki_info2': 'Explore famous destinations across Indonesia and learn useful phrases for your trip.',
      'wiki_info3': 'Where are you? Select your destination.',
      'wiki_info4': 'Tourist Destination',
      'wiki_des1': 'Island famous for beaches, temples, and vibrant culture.',
      'wiki_des2': 'Cultural heart of Java and home of Borobudur temple.',
      'wiki_des3': 'Bustling capital city blending culture, business and history.',
      'wiki_des4': 'One of the most beautiful marine paradises in the world',
      'wiki_info5': 'General Travel Tips for Indonesia',
      'wiki_info6': 'Essential Tips for All Travelers',
      'wiki_drop1': '• Learn basic Indonesian phrases - locals appreciate the effort',
      'wiki_drop2': '• Dress modestly, especially when visiting religious sites',
      'wiki_drop3': '• Always carry small bills (Rupiah) for local transactions',
      'wiki_drop4': '• Download offline maps before traveling to remote areas',
      'wiki_drop5': '• Try local street food from busy stalls (high turnover = fresh food)',
      'wiki_drop6': '• Negotiate prices at markets and with street vendors',
      'wiki_drop7': '• Use official taxis or ride-hailing apps (Gojek, Grab)',
      'wiki_drop8': '• Keep copies of important documents separately',
      'wiki_drop9': '• Purchase travel insurance before your trip',
      'wiki_drop10': '• Respect local customs and religious practices',
      'wiki_info7': 'Emergency Numbers in Indonesia',
      'wiki_info8': 'Save these important numbers before traveling',
      'wiki_em1': 'Police: 110',
      'wiki_em2': 'Ambulance: 118',
      'wiki_em3': 'Fire Department: 113',
      'wiki_all_destinations': 'All Destinations',
      'wiki_back': 'Back',
      'wiki_about_label': 'About {title}',
      'wiki_tab_attractions': 'Attractions',
      'wiki_tab_culture': 'Culture & Phrases',
      'wiki_tab_emergency': 'Emergency',
      'wiki_top_locations': 'Top Locations',
      'wiki_cultural_highlights': 'Cultural Highlights',
      'wiki_emergency_numbers': 'Emergency Numbers',

      // destinations
      'bali': 'Bali',
      'yogyakarta': 'Yogyakarta',
      'jakarta': 'Jakarta',
      'raja_ampat': 'Raja Ampat',

      // wiki content - bali attractions
      'bali_att_1': 'Kuta Beach',
      'bali_att_1_tip1': 'Sunset spot ideal for photography',
      'bali_att_1_tip2': 'Popular for surfing beginners',
      'bali_att_1_tip3': 'Close to cafes and restaurants',
      'bali_att_1_tip4': 'Easy access by scooter or car',
      'bali_att_2': 'Uluwatu Temple',
      'bali_att_2_tip1': 'Famous cliffside temple with ocean view',
      'bali_att_2_tip2': 'Cultural Kecak dance performances at sunset',
      'bali_att_2_tip3': 'Scenic photography spot',
      'bali_att_2_tip4': 'Watch out for monkeys!',
      'bali_att_3': 'Seminyak Beach',
      'bali_att_3_tip1': 'Trendy beach with cafes and bars',
      'bali_att_3_tip2': 'Great sunset watching spot',
      'bali_att_3_tip3': 'Water sports available',
      'bali_att_3_tip4': 'Busy but lively atmosphere',

      // wiki content - bali cultures
      'bali_cul_1': 'Balinese Dance',
      'bali_cul_1_det1': 'Traditional Kecak dance performance',
      'bali_cul_1_det2': 'Performed in temples during ceremonies',
      'bali_cul_1_det3': 'Storytelling through music and movement',
      'bali_cul_1_det4': 'Popular cultural experience for tourists',
      'bali_cul_2': 'Local Cuisine',
      'bali_cul_2_det1': 'Try Babi Guling (roast pig) and Lawar',
      'bali_cul_2_det2': 'Vibrant street food scene',
      'bali_cul_2_det3': 'Fresh ingredients from local markets',
      'bali_cul_2_det4': 'Spicy and flavorful dishes',
      'bali_cul_3': 'Useful Phrases',
      'bali_cul_3_det1': 'Om Swastiastu — Balinese greeting',
      'bali_cul_3_det2': 'Suksma — Thank you',
      'bali_cul_3_det3': 'Rahajeng semeng — Good morning',
      'bali_cul_3_det4': 'Ampura — Sorry / Excuse me',

      // wiki content - yogyakarta attractions
      'yogy_att_1': 'Borobudur Temple',
      'yogy_att_1_tip1': 'Largest Buddhist temple in the world',
      'yogy_att_1_tip2': 'Best visited at sunrise',
      'yogy_att_1_tip3': 'Wear modest clothing',
      'yogy_att_1_tip4': 'UNESCO World Heritage Site',
      'yogy_att_2': 'Prambanan Temple',
      'yogy_att_2_tip1': 'Stunning Hindu temple compound',
      'yogy_att_2_tip2': 'Light show at night available',
      'yogy_att_2_tip3': 'Close to Borobudur — great combo trip',
      'yogy_att_2_tip4': 'Beautiful at golden hour',
      'yogy_att_3': 'Keraton Yogyakarta',
      'yogy_att_3_tip1': 'Royal palace of the Sultan',
      'yogy_att_3_tip2': 'Cultural performances on weekends',
      'yogy_att_3_tip3': 'Guided tours available',
      'yogy_att_3_tip4': 'Rich history of Javanese royalty',

      // wiki content - yogyakarta cultures
      'yogy_cul_1': 'Wayang Kulit',
      'yogy_cul_1_det1': 'Traditional shadow puppet show',
      'yogy_cul_1_det2': 'Performed overnight in ceremonies',
      'yogy_cul_1_det3': 'Stories taken from Hindu epics (Ramayana, Mahabharata)',
      'yogy_cul_1_det4': 'A UNESCO Intangible Cultural Heritage',
      'yogy_cul_2': 'Batik Craft',
      'yogy_cul_2_det1': 'UNESCO-recognized art form',
      'yogy_cul_2_det2': 'Try making your own batik in workshops',
      'yogy_cul_2_det3': 'Malioboro is the best place to buy',
      'yogy_cul_2_det4': 'Motifs carry cultural meanings',
      'yogy_cul_3': 'Useful Phrases',
      'yogy_cul_3_det1': 'Sugeng rawuh — Welcome (Javanese)',
      'yogy_cul_3_det2': 'Matur nuwun — Thank you (Javanese)',
      'yogy_cul_3_det3': 'Mangga — Please / After you',
      'yogy_cul_3_det4': 'Nuwun sewu — Excuse me',

      // wiki content - jakarta attractions
      'jak_att_1': 'Old Town (Kota Tua)',
      'jak_att_1_tip1': 'Dutch colonial architecture',
      'jak_att_1_tip2': 'Museum Fatahillah nearby',
      'jak_att_1_tip3': 'Street food around the square',
      'jak_att_1_tip4': 'Great for history enthusiasts',
      'jak_att_2': 'Thousand Islands',
      'jak_att_2_tip1': 'Island getaway from the city',
      'jak_att_2_tip2': 'Snorkeling and diving spots',
      'jak_att_2_tip3': '1–2 hour boat ride from Muara Angke',
      'jak_att_2_tip4': 'Best visited on weekdays',
      'jak_att_3': 'Taman Mini Indonesia Indah',
      'jak_att_3_tip1': 'Cultural park showcasing all provinces',
      'jak_att_3_tip2': 'Family friendly destination',
      'jak_att_3_tip3': 'Wide area — best explored by vehicle',
      'jak_att_3_tip4': 'Traditional houses from every region',

      // wiki content - jakarta cultures
      'jak_cul_1': 'Betawi Culture',
      'jak_cul_1_det1': 'Indigenous culture of Jakarta',
      'jak_cul_1_det2': 'Ondel-ondel giant puppet dance',
      'jak_cul_1_det3': 'Kerak Telor: traditional sticky rice snack',
      'jak_cul_1_det4': 'Lenong: comedic folk theatre',
      'jak_cul_2': 'Modern Food Scene',
      'jak_cul_2_det1': 'Street food at Glodok (Chinatown)',
      'jak_cul_2_det2': 'Gado-gado and Soto Betawi are must-tries',
      'jak_cul_2_det3': 'Many international cuisines available',
      'jak_cul_2_det4': 'Food courts in malls are affordable',
      'jak_cul_3': 'Useful Phrases',
      'jak_cul_3_det1': 'Halo / Hai — Hello',
      'jak_cul_3_det2': 'Terima kasih — Thank you',
      'jak_cul_3_det3': 'Maaf — Sorry / Excuse me',
      'jak_cul_3_det4': 'Berapa harganya? — How much is it?',

      // wiki content - raja ampat attractions
      'ra_att_1': 'Wayag Islands',
      'ra_att_1_tip1': 'Iconic karst island view',
      'ra_att_1_tip2': 'Best reached by speedboat',
      'ra_att_1_tip3': 'Photography hotspot at sunrise',
      'ra_att_1_tip4': 'One of the most beautiful views in Indonesia',
      'ra_att_2': 'Pianemo',
      'ra_att_2_tip1': 'Lookout point over turquoise lagoon',
      'ra_att_2_tip2': 'Requires a short hike',
      'ra_att_2_tip3': 'Worth every step for the view',
      'ra_att_2_tip4': 'Great snorkeling below the viewpoint',
      'ra_att_3': 'Arborek Village',
      'ra_att_3_tip1': 'Traditional Papuan fishing village',
      'ra_att_3_tip2': 'Snorkeling right from the jetty',
      'ra_att_3_tip3': 'Support local handicrafts',
      'ra_att_3_tip4': 'Warm and welcoming community',

      // wiki content - raja ampat cultures
      'ra_cul_1': 'Papuan Traditions',
      'ra_cul_1_det1': 'Traditional dances with feather and shell costumes',
      'ra_cul_1_det2': 'Rich oral history and tribal culture',
      'ra_cul_1_det3': 'Respect local customs when visiting villages',
      'ra_cul_1_det4': 'Ask permission before taking photos of locals',
      'ra_cul_2': 'Local Food',
      'ra_cul_2_det1': 'Fresh seafood caught daily',
      'ra_cul_2_det2': 'Papeda (sago porridge) with fish soup',
      'ra_cul_2_det3': 'Unique flavors from eastern Indonesia',
      'ra_cul_2_det4': 'Pinang (betel nut) is commonly chewed locally',
      'ra_cul_3': 'Useful Phrases',
      'ra_cul_3_det1': 'Selamat datang — Welcome',
      'ra_cul_3_det2': 'Terima kasih — Thank you',
      'ra_cul_3_det3': 'Permisi — Excuse me',
      'ra_cul_3_det4': 'Tolong — Please / Help',

      // quiz screen
      'quiz_title': 'Quiz',
      'quiz_soal_progress': 'Question {current} / {total}',
      'quiz_hint': 'Write or record your answer...',
      'quiz_ref_answer': 'Reference answer:',
      'quiz_similarity': 'Similarity:',
      'quiz_submit': 'Submit Answer',
      'quiz_fill_first': 'Please fill in your answer first.',
      'quiz_analyzing': 'Your answer is being analyzed...',
      'quiz_finished': 'Quiz Finished!',
      'quiz_final_score': 'Your Final Score:',
      'quiz_correct_count': 'Correct {correct} out of {total} questions',
      'quiz_score_saved': 'Your score has been automatically saved in real-time.',
      'quiz_back_menu': 'Back to Menu',
      'quiz_status': 'Status:',
      'quiz_reason_label': 'Reason:',
      'quiz_next': 'Next Question',
      'quiz_done': 'Finish',
      'quiz_load_fail': 'Failed to load questions. Please try again.',
      'quiz_retry': 'Try Again',
      'quiz_no_questions': 'No questions available.',
      'status_correct': 'Correct',
      'status_partial': 'Almost Correct',
      'status_incorrect': 'Incorrect',
      'evaluated_by_gemini': 'Evaluated by Gemini',

      //Learning template
      'l_hint1': 'Scenario Completed!',
      'l_hint2': 'You finished all lessons. Ready for the quiz?',
      'l_completed': '{percent}% completed',
      'l_quiz_button': 'Start Quiz',
      'listening_top': 'Listen to the following audio',
      'listening_sub': 'Pay attention and continue to the next question',
      'writing_top': 'Write your answer',
      'writing_sub': 'Translate the following sentence into Indonesian',
      'speaking_top': 'Speak out loud',
      'speaking_sub': 'Read the sentence clearly',
      'question_title': 'Question {current} of {total}',
      'l_hint_writting': 'Type your answer in Indonesian.',
      'l_send': 'Submit',
      'answer_empty': 'Please fill in your answer first.',
      'answer_wrong': '❌ Incorrect answer.\n\nTip: Try writing "{correct}"',
      'answer_correct': '✅ Correct! Similarity: {score}%',
      'listening_status': 'Listening...',
      'mic_hint': 'Tap the microphone & speak...',
      'send_voice': 'Send Voice',
      'speaking_wrong': '❌ Incorrect. You said: "{spoken}".\n\nTip: Try saying "{correct}"',
      'all_done': 'All questions completed!',
      'l_next': 'Next',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'expert': 'Expert',
      'questions_not_available': 'Questions not available',
      'error_try_again': 'Something went wrong, please try again.',
      'learning_tab_listening': 'Listening',
      'learning_tab_writing': 'Writing',
      'learning_tab_speaking': 'Speaking',

      // auth
      'login_title': 'Wicara Wisata',
      'signin_tab': 'Sign In',
      'signup_tab': 'Sign Up',
      'email_label': 'Email',
      'password_label': 'Password',
      'username_label': 'Username',
      'forgot_password_link': 'Forgot Password?',
      'signin_button': 'Sign In',
      'signup_button': 'Sign Up',
      'create_account_button': 'Create Account',
      'continue_with_google': 'Continue with Google',
      'or_divider': 'OR',
      'auth_error_filling': 'All fields are required',
      'reset_password_title': 'Reset Your Password',
      'reset_password_desc': 'Enter your email below and we will send you a link to reset your password.',
      'send_reset_link_button': 'Send Reset Link',
      'back_to_login': 'Back to Login',
      'email_sent_title': 'Email Sent!',
      'email_sent_desc': 'A password reset link has been sent to:',
      'check_inbox_spam': 'Please check your inbox and spam folder.',

      // home additions
      'home_keep_it_up': '🔥 Keep it up!',
      'home_progress_of_lessons': '{current} of {total} lessons',
      'home_user_not_found': 'User data not found',
      'home_active_course': 'Active Course',
      'home_currently_working_on': 'Current Course',
      'home_completed_label': '{percent}% completed',

      // levels
      'select_your_level': '🎓 Select Your Level',
      'level_beginner': 'Beginner',
      'level_intermediate': 'Intermediate',
      'level_advanced': 'Advanced',

      // settings additions
      'logout_button': 'Logout',
      'logout_confirm_title': 'Logout',
      'logout_confirm_content': 'Are you sure you want to logout?',
      'cancel_button': 'Cancel',
      'changes_saved_msg': 'Changes saved!',
      'admin_tools_title': 'Admin Tools',
      'admin_upload_button': 'Open Question Uploader (Data Injection)',
      'no_scenarios_for_level': 'No scenarios available for the {level} level.',
    },

    'id': {
      //settings
      'settings_title': 'Pengaturan',
      'set_info': 'Kelola preferensi akun Anda',
      'profile_info': 'Informasi Profil',
      'update_details': 'Perbarui data pribadi Anda',
      'name': 'Nama',
      'email': 'Email',
      'email_cannot_change': 'Email tidak dapat diubah',
      'language_pref': 'Preferensi Bahasa',
      'choose_language': 'Pilih bahasa Anda',
      'recent_language': 'Bahasa Saat Ini:',
      'save_changes': 'Simpan Perubahan',
      'note_language_change': 'Catatan:\nPerubahan bahasa akan berlaku untuk semua pelajaran.',

      //home screens
      'welcome_user': 'Selamat datang, {name}',
      'info_home_1': 'Progress Keseluruhan',
      'quiz_info_1': 'Performa Kuis',
      'info_home_2': 'Mulai perjalanan Anda',
      'info_home_3': 'Mulai belajar Bahasa Indonesia hari ini',
      'info_home_4': 'Pilih dari 18 pelajaran dalam 3 tingkat kesulitan.',
      'info_home_5': 'Pelajari frasa penting untuk bandara, hotel, restoran, belanja, transportasi, dan fasilitas medis.',
      'info_home_6': 'Transportasi dan fasilitas medis.',
      'button_learn': 'Mulai Belajar',
      'info_home_7': 'Jelajahi Indonesia',
      'info_home_8': 'Destinasi Populer',
      'info_home_9': 'Tips Perjalanan',
      'info_home_10': 'Frasa Darurat',
      'info_home_11': 'Jelajahi Wiki',

      // levels
      'level_info': 'Pilih level Anda',
      'level_info_2': 'Pilih tingkat kesulitan untuk memulai perjalanan Anda',
      'lvl1': 'Pemula',
      'lvl1_sub': 'Percakapan sehari-hari dasar',
      'lvl2': 'Menengah',
      'lvl2_sub': 'Percakapan sehari-hari lanjutan',
      'lvl3': 'Mahir',
      'lvl3_sub': 'Komunikasi kompleks',
      'lvl_button': 'Mulai Belajar',

      //scenario
      'airport': 'Bandara',
      'airport_desc': 'Pelajari frasa dan tips di bandara.',
      'hotel': 'Hotel',
      'hotel_desc': 'Kalimat berguna untuk menginap di hotel.',
      'restaurant': 'Restoran',
      'restaurant_desc': 'Frasa dan kosakata makanan.',
      'shopping': 'Belanja',
      'shopping_desc': 'Kata dan tips saat berbelanja.',
      'market': 'Pasar',
      'market_desc': 'Frasa penting untuk belanja di pasar tradisional.',
      'transportation': 'Transportasi',
      'transportation_desc': 'Frasa untuk bepergian.',
      'hospital': 'Rumah Sakit',
      'hospital_desc': 'Frasa kesehatan dan darurat.',
      'clinic': 'Klinik',
      'clinic_desc': 'Skenario kesehatan dan berobat.',
      'start_learning': 'Mulai Belajar',

      //wiki
      'wiki_info1': 'Wiki Wisata Indonesia',
      'wiki_info2': 'Jelajahi destinasi terkenal di Indonesia dan pelajari frasa berguna untuk perjalananmu.',
      'wiki_info3': 'Di mana kamu berada? Pilih tujuanmu.',
      'wiki_info4': 'Destinasi Wisata',
      'wiki_des1': 'Pulau terkenal dengan pantai, candi, dan budaya yang hidup.',
      'wiki_des2': 'Jantung budaya Jawa dan rumah bagi Candi Borobudur.',
      'wiki_des3': 'Ibukota yang ramai memadukan budaya, bisnis, dan sejarah.',
      'wiki_des4': 'Salah satu surga laut paling indah di dunia',
      'wiki_info5': 'Tips Umum Perjalanan di Indonesia',
      'wiki_info6': 'Tips Penting untuk Semua Wisatawan',
      'wiki_drop1': '• Pelajari frasa dasar bahasa Indonesia – penduduk lokal menghargai usaha',
      'wiki_drop2': '• Berpakaian sopan, terutama saat mengunjungi tempat ibadah',
      'wiki_drop3': '• Selalu bawa uang kecil (Rupiah) untuk transaksi lokal',
      'wiki_drop4': '• Unduh peta offline sebelum ke daerah terpencil',
      'wiki_drop5': '• Cicipi makanan jalanan lokal dari warung ramai (lalu-lintas tinggi = makanan segar)',
      'wiki_drop6': '• Tawar-menawar harga di pasar dan dengan pedagang kaki lima',
      'wiki_drop7': '• Gunakan taksi resmi atau aplikasi ojek (Gojek, Grab)',
      'wiki_drop8': '• Simpan salinan dokumen penting secara terpisah',
      'wiki_drop9': '• Beli asuransi perjalanan sebelum perjalanan',
      'wiki_drop10': '• Hormati kebiasaan lokal dan praktik keagamaan',
      'wiki_info7': 'Nomor Darurat di Indonesia',
      'wiki_info8': 'Simpan nomor penting ini sebelum bepergian',
      'wiki_em1': 'Polisi: 110',
      'wiki_em2': 'Ambulans: 118',
      'wiki_em3': 'Pemadam Kebakaran: 113',
      'wiki_all_destinations': 'Semua Destinasi',
      'wiki_back': 'Kembali',
      'wiki_about_label': 'Tentang {title}',
      'wiki_tab_attractions': 'Atraksi',
      'wiki_tab_culture': 'Budaya & Frasa',
      'wiki_tab_emergency': 'Darurat',
      'wiki_top_locations': 'Lokasi Populer',
      'wiki_cultural_highlights': 'Sorotan Budaya',
      'wiki_emergency_numbers': 'Nomor Darurat',

      // destinations
      'bali': 'Bali',
      'yogyakarta': 'Yogyakarta',
      'jakarta': 'Jakarta',
      'raja_ampat': 'Raja Ampat',

      // wiki content - bali attractions
      'bali_att_1': 'Pantai Kuta',
      'bali_att_1_tip1': 'Spot matahari terbenam yang ideal untuk fotografi',
      'bali_att_1_tip2': 'Populer untuk pemula selancar',
      'bali_att_1_tip3': 'Dekat dengan kafe dan restoran',
      'bali_att_1_tip4': 'Mudah diakses dengan skuter atau mobil',
      'bali_att_2': 'Pura Uluwatu',
      'bali_att_2_tip1': 'Pura tepi tebing terkenal dengan pemandangan laut',
      'bali_att_2_tip2': 'Tari Kecak budaya saat matahari terbenam',
      'bali_att_2_tip3': 'Spot foto yang indah',
      'bali_att_2_tip4': 'Awas monyet!',
      'bali_att_3': 'Pantai Seminyak',
      'bali_att_3_tip1': 'Pantai trendi dengan kafe dan bar',
      'bali_att_3_tip2': 'Tempat menonton matahari terbenam yang bagus',
      'bali_att_3_tip3': 'Olahraga air tersedia',
      'bali_att_3_tip4': 'Ramai namun suasana meriah',

      // wiki content - bali cultures
      'bali_cul_1': 'Tarian Bali',
      'bali_cul_1_det1': 'Pertunjukan tari Kecak tradisional',
      'bali_cul_1_det2': 'Dipentaskan di pura saat upacara',
      'bali_cul_1_det3': 'Bercerita melalui musik dan gerakan',
      'bali_cul_1_det4': 'Pengalaman budaya populer bagi wisatawan',
      'bali_cul_2': 'Kuliner Lokal',
      'bali_cul_2_det1': 'Coba Babi Guling dan Lawar',
      'bali_cul_2_det2': 'Pemandangan makanan jalanan yang semarak',
      'bali_cul_2_det3': 'Bahan segar dari pasar lokal',
      'bali_cul_2_det4': 'Hidangan pedas dan kaya rasa',
      'bali_cul_3': 'Frasa Berguna',
      'bali_cul_3_det1': 'Om Swastiastu — Salam Bali',
      'bali_cul_3_det2': 'Suksma — Terima kasih',
      'bali_cul_3_det3': 'Rahajeng semeng — Selamat pagi',
      'bali_cul_3_det4': 'Ampura — Maaf / Permisi',

      // wiki content - yogyakarta attractions
      'yogy_att_1': 'Candi Borobudur',
      'yogy_att_1_tip1': 'Candi Buddha terbesar di dunia',
      'yogy_att_1_tip2': 'Terbaik dikunjungi saat matahari terbit',
      'yogy_att_1_tip3': 'Kenakan pakaian yang sopan',
      'yogy_att_1_tip4': 'Situs Warisan Dunia UNESCO',
      'yogy_att_2': 'Candi Prambanan',
      'yogy_att_2_tip1': 'Kompleks candi Hindu yang memukau',
      'yogy_att_2_tip2': 'Pertunjukan cahaya malam tersedia',
      'yogy_att_2_tip3': 'Dekat Borobudur — perjalanan kombo yang bagus',
      'yogy_att_2_tip4': 'Indah saat golden hour',
      'yogy_att_3': 'Keraton Yogyakarta',
      'yogy_att_3_tip1': 'Istana Sultan',
      'yogy_att_3_tip2': 'Pertunjukan budaya setiap akhir pekan',
      'yogy_att_3_tip3': 'Tur berpemandu tersedia',
      'yogy_att_3_tip4': 'Sejarah kaya kerajaan Jawa',

      // wiki content - yogyakarta cultures
      'yogy_cul_1': 'Wayang Kulit',
      'yogy_cul_1_det1': 'Pertunjukan boneka bayangan tradisional',
      'yogy_cul_1_det2': 'Dipentaskan semalam suntuk dalam upacara',
      'yogy_cul_1_det3': 'Kisah dari epos Hindu (Ramayana, Mahabharata)',
      'yogy_cul_1_det4': 'Warisan Budaya Tak Benda UNESCO',
      'yogy_cul_2': 'Kerajinan Batik',
      'yogy_cul_2_det1': 'Seni yang diakui UNESCO',
      'yogy_cul_2_det2': 'Coba membuat batik sendiri di workshop',
      'yogy_cul_2_det3': 'Malioboro adalah tempat terbaik untuk membeli',
      'yogy_cul_2_det4': 'Motif mengandung makna budaya',
      'yogy_cul_3': 'Frasa Berguna',
      'yogy_cul_3_det1': 'Sugeng rawuh — Selamat datang (Jawa)',
      'yogy_cul_3_det2': 'Matur nuwun — Terima kasih (Jawa)',
      'yogy_cul_3_det3': 'Mangga — Silakan / Dipersilakan',
      'yogy_cul_3_det4': 'Nuwun sewu — Permisi',

      // wiki content - jakarta attractions
      'jak_att_1': 'Kota Tua',
      'jak_att_1_tip1': 'Arsitektur kolonial Belanda',
      'jak_att_1_tip2': 'Museum Fatahillah di dekatnya',
      'jak_att_1_tip3': 'Makanan jalanan di sekitar alun-alun',
      'jak_att_1_tip4': 'Cocok bagi pecinta sejarah',
      'jak_att_2': 'Kepulauan Seribu',
      'jak_att_2_tip1': 'Liburan pulau dari hiruk pikuk kota',
      'jak_att_2_tip2': 'Spot snorkeling dan menyelam',
      'jak_att_2_tip3': 'Naik kapal 1–2 jam dari Muara Angke',
      'jak_att_2_tip4': 'Terbaik dikunjungi saat hari kerja',
      'jak_att_3': 'Taman Mini Indonesia Indah',
      'jak_att_3_tip1': 'Taman budaya menampilkan semua provinsi',
      'jak_att_3_tip2': 'Destinasi ramah keluarga',
      'jak_att_3_tip3': 'Area luas — terbaik dijelajahi dengan kendaraan',
      'jak_att_3_tip4': 'Rumah adat dari setiap daerah',

      // wiki content - jakarta cultures
      'jak_cul_1': 'Budaya Betawi',
      'jak_cul_1_det1': 'Budaya asli Jakarta',
      'jak_cul_1_det2': 'Tari boneka raksasa Ondel-ondel',
      'jak_cul_1_det3': 'Kerak Telor: camilan nasi ketan tradisional',
      'jak_cul_1_det4': 'Lenong: teater rakyat komedi',
      'jak_cul_2': 'Kuliner Modern',
      'jak_cul_2_det1': 'Makanan jalanan di Glodok (Pecinan)',
      'jak_cul_2_det2': 'Gado-gado dan Soto Betawi wajib dicoba',
      'jak_cul_2_det3': 'Banyak masakan internasional tersedia',
      'jak_cul_2_det4': 'Food court di mal terjangkau',
      'jak_cul_3': 'Frasa Berguna',
      'jak_cul_3_det1': 'Halo / Hai — Halo',
      'jak_cul_3_det2': 'Terima kasih — Terima kasih',
      'jak_cul_3_det3': 'Maaf — Maaf / Permisi',
      'jak_cul_3_det4': 'Berapa harganya? — Berapa harganya?',

      // wiki content - raja ampat attractions
      'ra_att_1': 'Kepulauan Wayag',
      'ra_att_1_tip1': 'Pemandangan pulau karst ikonik',
      'ra_att_1_tip2': 'Terbaik dicapai dengan speedboat',
      'ra_att_1_tip3': 'Spot foto saat matahari terbit',
      'ra_att_1_tip4': 'Salah satu pemandangan terindah di Indonesia',
      'ra_att_2': 'Pianemo',
      'ra_att_2_tip1': 'Titik pandang di atas laguna berwarna pirus',
      'ra_att_2_tip2': 'Memerlukan pendakian singkat',
      'ra_att_2_tip3': 'Sepadan untuk pemandangannya',
      'ra_att_2_tip4': 'Snorkeling bagus di bawah titik pandang',
      'ra_att_3': 'Desa Arborek',
      'ra_att_3_tip1': 'Desa nelayan tradisional Papua',
      'ra_att_3_tip2': 'Snorkeling langsung dari dermaga',
      'ra_att_3_tip3': 'Dukung kerajinan lokal',
      'ra_att_3_tip4': 'Komunitas yang hangat dan ramah',

      // wiki content - raja ampat cultures
      'ra_cul_1': 'Tradisi Papua',
      'ra_cul_1_det1': 'Tarian tradisional dengan kostum bulu dan kerang',
      'ra_cul_1_det2': 'Sejarah lisan dan budaya suku yang kaya',
      'ra_cul_1_det3': 'Hormati adat lokal saat mengunjungi desa',
      'ra_cul_1_det4': 'Minta izin sebelum memotret warga lokal',
      'ra_cul_2': 'Kuliner Lokal',
      'ra_cul_2_det1': 'Hasil laut segar tangkapan harian',
      'ra_cul_2_det2': 'Papeda (bubur sagu) dengan sup ikan',
      'ra_cul_2_det3': 'Cita rasa unik dari Indonesia timur',
      'ra_cul_2_det4': 'Pinang umumnya dikunyah oleh warga lokal',
      'ra_cul_3': 'Frasa Berguna',
      'ra_cul_3_det1': 'Selamat datang — Welcome',
      'ra_cul_3_det2': 'Terima kasih — Thank you',
      'ra_cul_3_det3': 'Permisi — Excuse me',
      'ra_cul_3_det4': 'Tolong — Please / Help',

      // quiz screen
      'quiz_title': 'Kuis',
      'quiz_soal_progress': 'Soal {current} / {total}',
      'quiz_hint': 'Tulis atau rekam jawaban...',
      'quiz_ref_answer': 'Jawaban referensi:',
      'quiz_similarity': 'Kemiripan:',
      'quiz_submit': 'Kirim Jawaban',
      'quiz_fill_first': 'Silakan isi jawaban dulu.',
      'quiz_analyzing': 'Jawabanmu sedang dianalisis...',
      'quiz_finished': 'Kuis Selesai!',
      'quiz_final_score': 'Nilai Akhir Anda:',
      'quiz_correct_count': 'Benar {correct} dari {total} soal',
      'quiz_score_saved': 'Nilai Anda telah otomatis disimpan secara real-time.',
      'quiz_back_menu': 'Kembali ke Menu',
      'quiz_status': 'Status:',
      'quiz_reason_label': 'Alasan:',
      'quiz_next': 'Soal Berikutnya',
      'quiz_done': 'Selesai',
      'quiz_load_fail': 'Gagal memuat soal. Coba lagi.',
      'quiz_retry': 'Coba Lagi',
      'quiz_no_questions': 'Soal belum tersedia.',
      'status_correct': 'Benar',
      'status_partial': 'Hampir Benar',
      'status_incorrect': 'Kurang Tepat',
      'evaluated_by_gemini': 'Dievaluasi oleh Gemini',

      //Learning template
      'l_hint1': 'Skenario Selesai!',
      'l_hint2': 'Kamu menyelesaikan semua pelajaran. Siap untuk kuis?',
      'l_completed': '{percent}% selesai',
      'l_quiz_button': 'Mulai Kuis',
      'listening_top': 'Dengarkan audio berikut',
      'listening_sub': 'Perhatikan baik-baik dan lanjutkan ke pertanyaan berikutnya',
      'writing_top': 'Tulis jawabanmu',
      'writing_sub': 'Terjemahkan kalimat berikut ke dalam bahasa Indonesia',
      'speaking_top': 'Ucapkan dengan keras',
      'speaking_sub': 'Baca kalimat dengan jelas',
      'question_title': 'Pertanyaan {current} dari {total}',
      'l_hint_writting': 'Ketik jawabanmu dalam bahasa Indonesia.',
      'l_send': 'Kirim',
      'answer_empty': 'Tolong isi jawabanmu terlebih dahulu.',
      'answer_wrong': '❌ Jawaban salah.\n\nTips: Coba tulis "{correct}"',
      'answer_correct': '✅ Benar! Kemiripan: {score}%',
      'listening_status': 'Sedang mendengarkan...',
      'mic_hint': 'Ketuk mikrofon & bicara...',
      'send_voice': 'Kirim Suara',
      'speaking_wrong': '❌ Salah. Kamu berkata: "{spoken}".\n\nTips: Coba ucapkan "{correct}"',
      'all_done': 'Semua pertanyaan selesai!',
      'l_next': 'Lanjut',
      'beginner': 'Pemula',
      'intermediate': 'Menengah',
      'advanced': 'Lanjutan',
      'expert': 'Ahli',
      'questions_not_available': 'Pertanyaan tidak tersedia',
      'error_try_again': 'Terjadi kesalahan, silakan coba lagi.',
      'learning_tab_listening': 'Mendengar',
      'learning_tab_writing': 'Menulis',
      'learning_tab_speaking': 'Berbicara',

      // auth
      'login_title': 'Wicara Wisata',
      'signin_tab': 'Masuk',
      'signup_tab': 'Daftar',
      'email_label': 'Email',
      'password_label': 'Kata Sandi',
      'username_label': 'Nama Pengguna',
      'forgot_password_link': 'Lupa Kata Sandi?',
      'signin_button': 'Masuk',
      'signup_button': 'Daftar',
      'create_account_button': 'Buat Akun',
      'continue_with_google': 'Lanjutkan dengan Google',
      'or_divider': 'ATAU',
      'auth_error_filling': 'Semua kolom wajib diisi',
      'reset_password_title': 'Atur Ulang Kata Sandi',
      'reset_password_desc': 'Masukkan email Anda di bawah ini dan kami akan mengirimkan tautan untuk mengatur ulang kata sandi Anda.',
      'send_reset_link_button': 'Kirim Tautan Atur Ulang',
      'back_to_login': 'Kembali ke Masuk',
      'email_sent_title': 'Email Terkirim!',
      'email_sent_desc': 'Tautan atur ulang kata sandi telah dikirim ke:',
      'check_inbox_spam': 'Silakan periksa kotak masuk dan folder spam Anda.',

      // home additions
      'home_keep_it_up': '🔥 Semangat terus!',
      'home_progress_of_lessons': '{current} dari {total} pelajaran',
      'home_user_not_found': 'Data pengguna tidak ditemukan',
      'home_active_course': 'Kursus Aktif',
      'home_currently_working_on': 'Sedang Dipelajari',
      'home_completed_label': '{percent}% selesai',

      // levels
      'select_your_level': '🎓 Pilih Level Anda',
      'level_beginner': 'Pemula',
      'level_intermediate': 'Menengah',
      'level_advanced': 'Mahir',

      // settings additions
      'logout_button': 'Keluar',
      'logout_confirm_title': 'Keluar',
      'logout_confirm_content': 'Apakah Anda yakin ingin keluar?',
      'cancel_button': 'Batal',
      'changes_saved_msg': 'Perubahan disimpan!',
      'admin_tools_title': 'Alat Admin',
      'admin_upload_button': 'Buka Pengunggah Soal (Suntik Data)',
      'no_scenarios_for_level': 'Belum ada skenario untuk level {level}.',
    },

    'es': {
      // settings
      'settings_title': 'Configuración',
      'set_info': 'Administra las preferencias de tu cuenta',
      'profile_info': 'Información del perfil',
      'update_details': 'Actualiza tus datos personales',
      'name': 'Nombre',
      'email': 'Correo electrónico',
      'email_cannot_change': 'El correo electrónico no se puede cambiar',
      'language_pref': 'Preferencias de idioma',
      'choose_language': 'Elige tu idioma',
      'recent_language': 'Idioma actual:',
      'save_changes': 'Guardar cambios',
      'note_language_change': 'Nota:\nEl cambio de idioma se aplicará a todas las lecciones.',

      // home screens
      'welcome_user': 'Bienvenido, {name}',
      'info_home_1': 'Progreso general',
      'quiz_info_1': 'Rendimiento del cuestionario',
      'info_home_2': 'Comienza tu viaje',
      'info_home_3': 'Empieza a aprender indonesio hoy',
      'info_home_4': 'Elige entre 18 lecciones en 3 niveles de dificultad.',
      'info_home_5': 'Aprende frases esenciales para aeropuertos, hoteles, restaurantes, compras, transporte y servicios médicos.',
      'info_home_6': 'Transporte y servicios médicos.',
      'button_learn': 'Comenzar a aprender',
      'info_home_7': 'Explorar Indonesia',
      'info_home_8': 'Destinos populares',
      'info_home_9': 'Consejos de viaje',
      'info_home_10': 'Frases de emergencia',
      'info_home_11': 'Explorar Wiki',

      // levels
      'level_info': 'Elige tu nivel',
      'level_info_2': 'Selecciona un nivel de dificultad para comenzar tu viaje',
      'lvl1': 'Principiante',
      'lvl1_sub': 'Conversación diaria básica',
      'lvl2': 'Intermedio',
      'lvl2_sub': 'Conversación diaria avanzada',
      'lvl3': 'Experto',
      'lvl3_sub': 'Comunicación compleja',
      'lvl_button': 'Comenzar a aprender',

      // scenario
      'airport': 'Aeropuerto',
      'airport_desc': 'Aprende frases y consejos del aeropuerto.',
      'hotel': 'Hotel',
      'hotel_desc': 'Frases útiles para estadías en hotel.',
      'restaurant': 'Restaurante',
      'restaurant_desc': 'Frases y vocabulario de comida.',
      'shopping': 'Compras',
      'shopping_desc': 'Palabras y consejos para comprar.',
      'market': 'Mercado',
      'market_desc': 'Frases esenciales para mercados tradicionales.',
      'transportation': 'Transporte',
      'transportation_desc': 'Frases para moverse.',
      'hospital': 'Hospital',
      'hospital_desc': 'Frases médicas y de emergencia.',
      'clinic': 'Clínica',
      'clinic_desc': 'Escenarios médicos y frases de tratamiento.',
      'start_learning': 'Comenzar a aprender',

      // wiki
      'wiki_info1': 'Wiki Turística de Indonesia',
      'wiki_info2': 'Explora destinos famosos en Indonesia y aprende frases útiles para tu viaje.',
      'wiki_info3': '¿Dónde estás? Selecciona tu destino.',
      'wiki_info4': 'Destino Turístico',
      'wiki_des1': 'Isla famosa por sus playas, templos y cultura vibrante.',
      'wiki_des2': 'Corazón cultural de Java y hogar del templo Borobudur.',
      'wiki_des3': 'Capital bulliciosa que combina cultura, negocios e historia.',
      'wiki_des4': 'Uno de los paraísos marinos más hermosos del mundo',
      'wiki_info5': 'Consejos Generales de Viaje en Indonesia',
      'wiki_info6': 'Consejos esenciales para todos los viajeros',
      'wiki_drop1': '• Aprende frases básicas en indonesio – los locales aprecian el esfuerzo',
      'wiki_drop2': '• Viste de manera modesta, especialmente al visitar sitios religiosos',
      'wiki_drop3': '• Lleva siempre billetes pequeños (Rupia) para transacciones locales',
      'wiki_drop4': '• Descarga mapas offline antes de viajar a zonas remotas',
      'wiki_drop5': '• Prueba la comida callejera local en puestos concurridos (alto movimiento = comida fresca)',
      'wiki_drop6': '• Negocia precios en mercados y con vendedores ambulantes',
      'wiki_drop7': '• Usa taxis oficiales o apps de transporte (Gojek, Grab)',
      'wiki_drop8': '• Guarda copias de documentos importantes por separado',
      'wiki_drop9': '• Contrata un seguro de viaje antes de tu viaje',
      'wiki_drop10': '• Respeta las costumbres locales y prácticas religiosas',
      'wiki_info7': 'Números de Emergencia en Indonesia',
      'wiki_info8': 'Guarda estos números importantes antes de viajar',
      'wiki_em1': 'Policía: 110',
      'wiki_em2': 'Ambulancia: 118',
      'wiki_em3': 'Bomberos: 113',
      'wiki_all_destinations': 'Todos los destinos',
      'wiki_back': 'Atrás',
      'wiki_about_label': 'Sobre {title}',
      'wiki_tab_attractions': 'Atracciones',
      'wiki_tab_culture': 'Cultura & Frases',
      'wiki_tab_emergency': 'Emergencia',
      'wiki_top_locations': 'Top lugares',
      'wiki_cultural_highlights': 'Cultura destacada',
      'wiki_emergency_numbers': 'Números de emergencia',

      // destinations
      'bali': 'Bali',
      'yogyakarta': 'Yogyakarta',
      'jakarta': 'Jakarta',
      'raja_ampat': 'Raja Ampat',

      // wiki content - bali attractions
      'bali_att_1': 'Playa de Kuta',
      'bali_att_1_tip1': 'Lugar ideal para fotos al atardecer',
      'bali_att_1_tip2': 'Popular para principiantes de surf',
      'bali_att_1_tip3': 'Cerca de cafés y restaurantes',
      'bali_att_1_tip4': 'Fácil acceso en scooter o coche',
      'bali_att_2': 'Templo de Uluwatu',
      'bali_att_2_tip1': 'Famoso templo en acantilado con vista al mar',
      'bali_att_2_tip2': 'Danza Kecak cultural al atardecer',
      'bali_att_2_tip3': 'Punto de fotografía panorámica',
      'bali_att_2_tip4': '¡Cuidado con los monos!',
      'bali_att_3': 'Playa de Seminyak',
      'bali_att_3_tip1': 'Playa moderna con cafés y bares',
      'bali_att_3_tip2': 'Lugar ideal para ver el atardecer',
      'bali_att_3_tip3': 'Deportes acuáticos disponibles',
      'bali_att_3_tip4': 'Ambiente animado y lleno de vida',

      // wiki content - bali cultures
      'bali_cul_1': 'Danza balinesa',
      'bali_cul_1_det1': 'Espectáculo de danza Kecak tradicional',
      'bali_cul_1_det2': 'Realizada en templos durante ceremonias',
      'bali_cul_1_det3': 'Narrativa a través de música y movimiento',
      'bali_cul_1_det4': 'Experiencia cultural popular para turistas',
      'bali_cul_2': 'Cocina Local',
      'bali_cul_2_det1': 'Prueba el Babi Guling (lechón asado) y Lawar',
      'bali_cul_2_det2': 'Vibrante escena de comida callejera',
      'bali_cul_2_det3': 'Ingredientes frescos de mercados locales',
      'bali_cul_2_det4': 'Platos picantes y llenos de sabor',
      'bali_cul_3': 'Frases Útiles',
      'bali_cul_3_det1': 'Om Swastiastu — Saludo balinés',
      'bali_cul_3_det2': 'Suksma — Gracias',
      'bali_cul_3_det3': 'Rahajeng semeng — Buenos días',
      'bali_cul_3_det4': 'Ampura — Lo siento / Permiso',

      // wiki content - yogyakarta attractions
      'yogy_att_1': 'Templo Borobudur',
      'yogy_att_1_tip1': 'El templo budista más grande del mundo',
      'yogy_att_1_tip2': 'Lo mejor es visitarlo al amanecer',
      'yogy_att_1_tip3': 'Viste de forma modesta',
      'yogy_att_1_tip4': 'Sitio Patrimonio Mundial UNESCO',
      'yogy_att_2': 'Templo Prambanan',
      'yogy_att_2_tip1': 'Impresionante complejo de templos hindúes',
      'yogy_att_2_tip2': 'Espectáculo de luces nocturno disponible',
      'yogy_att_2_tip3': 'Cerca de Borobudur — gran combinación',
      'yogy_att_2_tip4': 'Hermoso en la hora dorada',
      'yogy_att_3': 'Keraton Yogyakarta',
      'yogy_att_3_tip1': 'Palacio real del Sultán',
      'yogy_att_3_tip2': 'Actuaciones culturales los fines de semana',
      'yogy_att_3_tip3': 'Tours guiados disponibles',
      'yogy_att_3_tip4': 'Rica historia de la realeza javanesa',

      // wiki content - yogyakarta cultures
      'yogy_cul_1': 'Wayang Kulit',
      'yogy_cul_1_det1': 'Espectáculo tradicional de marionetas de sombra',
      'yogy_cul_1_det2': 'Realizado durante toda la noche en ceremonias',
      'yogy_cul_1_det3': 'Historias de épicas hindúes (Ramayana, Mahabharata)',
      'yogy_cul_1_det4': 'Patrimonio Cultural Inmaterial de la UNESCO',
      'yogy_cul_2': 'Artesanía Batik',
      'yogy_cul_2_det1': 'Arte reconocido por la UNESCO',
      'yogy_cul_2_det2': 'Prueba hacer tu propio batik en talleres',
      'yogy_cul_2_det3': 'Malioboro es el mejor lugar para comprar',
      'yogy_cul_2_det4': 'Los motivos tienen significados culturales',
      'yogy_cul_3': 'Frases Útiles',
      'yogy_cul_3_det1': 'Sugeng rawuh — Bienvenido (javanés)',
      'yogy_cul_3_det2': 'Matur nuwun — Gracias (javanés)',
      'yogy_cul_3_det3': 'Mangga — Por favor / Pase usted',
      'yogy_cul_3_det4': 'Nuwun sewu — Permiso',

      // wiki content - jakarta attractions
      'jak_att_1': 'Ciudad Vieja (Kota Tua)',
      'jak_att_1_tip1': 'Arquitectura colonial holandesa',
      'jak_att_1_tip2': 'Museo Fatahillah cerca',
      'jak_att_1_tip3': 'Comida callejera alrededor de la plaza',
      'jak_att_1_tip4': 'Perfecto para amantes de la historia',
      'jak_att_2': 'Las Mil Islas',
      'jak_att_2_tip1': 'Escapada isleña desde la ciudad',
      'jak_att_2_tip2': 'Puntos de snorkel y buceo',
      'jak_att_2_tip3': '1–2 horas en barco desde Muara Angke',
      'jak_att_2_tip4': 'Mejor visitarlas entre semana',
      'jak_att_3': 'Taman Mini Indonesia Indah',
      'jak_att_3_tip1': 'Parque cultural con todas las provincias',
      'jak_att_3_tip2': 'Destino familiar',
      'jak_att_3_tip3': 'Área amplia — mejor explorar en vehículo',
      'jak_att_3_tip4': 'Casas tradicionales de cada región',

      // wiki content - jakarta cultures
      'jak_cul_1': 'Cultura Betawi',
      'jak_cul_1_det1': 'Cultura indígena de Yakarta',
      'jak_cul_1_det2': 'Danza de marionetas gigantes Ondel-ondel',
      'jak_cul_1_det3': 'Kerak Telor: aperitivo tradicional de arroz glutinoso',
      'jak_cul_1_det4': 'Lenong: teatro popular cómico',
      'jak_cul_2': 'Escena Gastronómica Moderna',
      'jak_cul_2_det1': 'Comida callejera en Glodok (Barrio Chino)',
      'jak_cul_2_det2': 'Gado-gado y Soto Betawi son imperdibles',
      'jak_cul_2_det3': 'Muchas cocinas internacionales disponibles',
      'jak_cul_2_det4': 'Los patios de comida en centros comerciales son asequibles',
      'jak_cul_3': 'Frases Útiles',
      'jak_cul_3_det1': 'Halo / Hai — Hola',
      'jak_cul_3_det2': 'Terima kasih — Gracias',
      'jak_cul_3_det3': 'Maaf — Lo siento / Permiso',
      'jak_cul_3_det4': 'Berapa harganya? — ¿Cuánto cuesta?',

      // wiki content - raja ampat attractions
      'ra_att_1': 'Islas Wayag',
      'ra_att_1_tip1': 'Vista icónica de islas kársticas',
      'ra_att_1_tip2': 'Mejor llegar en lancha rápida',
      'ra_att_1_tip3': 'Lugar de fotografía al amanecer',
      'ra_att_1_tip4': 'Una de las vistas más hermosas de Indonesia',
      'ra_att_2': 'Pianemo',
      'ra_att_2_tip1': 'Mirador sobre una laguna turquesa',
      'ra_att_2_tip2': 'Requiere una pequeña caminata',
      'ra_att_2_tip3': 'Vale cada paso por la vista',
      'ra_att_2_tip4': 'Excelente snorkel bajo el mirador',
      'ra_att_3': 'Pueblo Arborek',
      'ra_att_3_tip1': 'Pueblo pesquero tradicional de Papúa',
      'ra_att_3_tip2': 'Snorkel directo desde el muelle',
      'ra_att_3_tip3': 'Apoya las artesanías locales',
      'ra_att_3_tip4': 'Comunidad cálida y acogedora',

      // wiki content - raja ampat cultures
      'ra_cul_1': 'Tradiciones de Papúa',
      'ra_cul_1_det1': 'Danzas tradicionales con trajes de plumas y conchas',
      'ra_cul_1_det2': 'Rica historia oral y cultura tribal',
      'ra_cul_1_det3': 'Respeta las costumbres locales al visitar aldeas',
      'ra_cul_1_det4': 'Pide permiso antes de fotografiar a los locales',
      'ra_cul_2': 'Comida Local',
      'ra_cul_2_det1': 'Mariscos frescos pescados diariamente',
      'ra_cul_2_det2': 'Papeda (gachas de sagú) con sopa de pescado',
      'ra_cul_2_det3': 'Sabores únicos del este de Indonesia',
      'ra_cul_2_det4': 'El pinang (nuez de betel) es masticado localmente',
      'ra_cul_3': 'Frases Útiles',
      'ra_cul_3_det1': 'Selamat datang — Bienvenido',
      'ra_cul_3_det2': 'Terima kasih — Gracias',
      'ra_cul_3_det3': 'Permisi — Permiso',
      'ra_cul_3_det4': 'Tolong — Por favor / Ayuda',

      // quiz screen
      'quiz_title': 'Cuestionario',
      'quiz_soal_progress': 'Pregunta {current} / {total}',
      'quiz_hint': 'Escribe o graba tu respuesta...',
      'quiz_ref_answer': 'Respuesta de referencia:',
      'quiz_similarity': 'Similitud:',
      'quiz_submit': 'Enviar Respuesta',
      'quiz_fill_first': 'Por favor, escribe tu respuesta primero.',
      'quiz_analyzing': 'Tu respuesta está siendo analizada...',
      'quiz_finished': '¡Cuestionario Terminado!',
      'quiz_final_score': 'Tu Puntuación Final:',
      'quiz_correct_count': '{correct} correctas de {total} preguntas',
      'quiz_score_saved': 'Tu puntuación se ha guardado automáticamente en tiempo real.',
      'quiz_back_menu': 'Volver al Menú',
      'quiz_status': 'Estado:',
      'quiz_reason_label': 'Razón:',
      'quiz_next': 'Siguiente Pregunta',
      'quiz_done': 'Terminar',
      'quiz_load_fail': 'Error al cargar preguntas. Inténtalo de nuevo.',
      'quiz_retry': 'Intentar de Nuevo',
      'quiz_no_questions': 'No hay preguntas disponibles.',
      'status_correct': 'Correcto',
      'status_partial': 'Casi Correcto',
      'status_incorrect': 'Incorrecto',
      'evaluated_by_gemini': 'Evaluado por Gemini',

      //Learning template
      'l_hint1': '¡Escenario completado!',
      'l_hint2': 'Terminaste todas las lecciones. ¿Listo para el cuestionario?',
      'l_completed': '{percent}% completado',
      'l_quiz_button': 'Iniciar cuestionario',
      'listening_top': 'Escucha el siguiente audio',
      'listening_sub': 'Presta atención y continúa con la siguiente pregunta',
      'writing_top': 'Escribe tu respuesta',
      'writing_sub': 'Traduce la siguiente oración al indonesio',
      'speaking_top': 'Habla en voz alta',
      'speaking_sub': 'Lee la oración claramente',
      'question_title': 'Pregunta {current} de {total}',
      'l_hint_writting': 'Escribe tu respuesta en indonesio.',
      'l_send': 'Enviar',
      'answer_empty': 'Por favor completa tu respuesta primero.',
      'answer_wrong': '❌ Respuesta incorrecta.\n\nConsejo: Intenta escribir "{correct}"',
      'answer_correct': '✅ ¡Correcto! Similitud: {score}%',
      'listening_status': 'Escuchando...',
      'mic_hint': 'Toca el micrófono y habla...',
      'send_voice': 'Enviar voz',
      'speaking_wrong': '❌ Incorrecto. Dijiste: "{spoken}".\n\nConsejo: Intenta decir "{correct}"',
      'all_done': '¡Todas las preguntas completadas!',
      'l_next': 'Siguiente',
      'beginner': 'Principiante',
      'intermediate': 'Intermedio',
      'advanced': 'Avanzado',
      'expert': 'Experto',
      'questions_not_available': 'Preguntas no disponibles',
      'error_try_again': 'Algo salió mal, por favor inténtalo de nuevo.',
      'learning_tab_listening': 'Escuchando',
      'learning_tab_writing': 'Escribiendo',
      'learning_tab_speaking': 'Hablando',

      // auth
      'login_title': 'Wicara Wisata',
      'signin_tab': 'Iniciar sesión',
      'signup_tab': 'Registrarse',
      'email_label': 'Correo electrónico',
      'password_label': 'Contraseña',
      'username_label': 'Nombre de usuario',
      'forgot_password_link': '¿Olvidaste tu contraseña?',
      'signin_button': 'Iniciar sesión',
      'signup_button': 'Registrarse',
      'create_account_button': 'Crear cuenta',
      'continue_with_google': 'Continuar con Google',
      'or_divider': 'O',
      'auth_error_filling': 'Todos los campos son obligatorios',
      'reset_password_title': 'Restablecer contraseña',
      'reset_password_desc': 'Ingresa tu correo abajo y te enviaremos un enlace.',
      'send_reset_link_button': 'Enviar enlace',
      'back_to_login': 'Volver al inicio',
      'email_sent_title': '¡Email enviado!',
      'email_sent_desc': 'Se ha enviado un enlace a:',
      'check_inbox_spam': 'Revisa tu bandeja de entrada y spam.',

      // home additions
      'home_keep_it_up': '🔥 ¡Sigue así!',
      'home_progress_of_lessons': '{current} de {total} lecciones',
      'home_user_not_found': 'Usuario no encontrado',
      'home_active_course': 'Curso activo',
      'home_currently_working_on': 'Curso actual',
      'home_completed_label': '{percent}% completado',

      // levels
      'select_your_level': '🎓 Elige tu nivel',
      'level_beginner': 'Principiante',
      'level_intermediate': 'Intermedio',
      'level_advanced': 'Avanzado',

      // settings additions
      'logout_button': 'Cerrar sesión',
      'logout_confirm_title': 'Cerrar sesión',
      'logout_confirm_content': '¿Seguro que quieres salir?',
      'cancel_button': 'Cancelar',
      'changes_saved_msg': '¡Cambios guardados!',
      'admin_tools_title': 'Admin',
      'admin_upload_button': 'Cargador de datos',
      'no_scenarios_for_level': 'No hay escenarios disponibles para el nivel {level}.',
    },

    'ru': {
      // settings
      'settings_title': 'Настройки',
      'set_info': 'Управление настройками аккаунта',
      'profile_info': 'Информация профиля',
      'update_details': 'Обновите личные данные',
      'name': 'Имя',
      'email': 'Электронная почта',
      'email_cannot_change': 'Электронную почту нельзя изменить',
      'language_pref': 'Языковые настройки',
      'choose_language': 'Выберите язык',
      'recent_language': 'Текущий язык:',
      'save_changes': 'Сохранить изменения',
      'note_language_change': 'Примечание:\nСмена языка применится ко всем урокам.',

      // home screens
      'welcome_user': 'Добро пожаловать, {name}',
      'info_home_1': 'Общий прогресс',
      'quiz_info_1': 'Результаты тестов',
      'info_home_2': 'Начните своё путешествие',
      'info_home_3': 'Начните изучать индонезийский уже сегодня',
      'info_home_4': 'Выберите из 18 уроков в 3 уровнях сложности.',
      'info_home_5': 'Изучите важные фразы для аэропортов, отелей, ресторанов, покупок, транспорта и медицинских услуг.',
      'info_home_6': 'Транспорт и медицинские услуги.',
      'button_learn': 'Начать обучение',
      'info_home_7': 'Исследуйте Индонезию',
      'info_home_8': 'Популярные направления',
      'info_home_9': 'Советы путешественникам',
      'info_home_10': 'Экстренные фразы',
      'info_home_11': 'Открыть Wiki',

      // levels
      'level_info': 'Выберите уровень',
      'level_info_2': 'Выберите уровень сложности, чтобы начать',
      'lvl1': 'Начальный',
      'lvl1_sub': 'Базовый разговорный уровень',
      'lvl2': 'Средний',
      'lvl2_sub': 'Продвинутый разговорный уровень',
      'lvl3': 'Продвинутый',
      'lvl3_sub': 'Сложная коммуникация',
      'lvl_button': 'Начать обучение',

      // scenario
      'airport': 'Аэропорт',
      'airport_desc': 'Изучите фразы и советы для аэропорта.',
      'hotel': 'Отель',
      'hotel_desc': 'Полезные фразы для проживания в отеле.',
      'restaurant': 'Ресторан',
      'restaurant_desc': 'Фразы и словарный запас для еды.',
      'shopping': 'Покупки',
      'shopping_desc': 'Слова и советы для покупок.',
      'market': 'Рынок',
      'market_desc': 'Основные фразы для традиционных рынков.',
      'transportation': 'Транспорт',
      'transportation_desc': 'Фразы для передвижения.',
      'hospital': 'Больница',
      'hospital_desc': 'Медицинские и экстренные фразы.',
      'clinic': 'Клиника',
      'clinic_desc': 'Медицинские сценарии и фразы для лечения.',
      'start_learning': 'Начать обучение',

      // wiki
      'wiki_info1': 'Туристическая Википедия Индонезии',
      'wiki_info2': 'Исследуйте известные места Индонезии и выучите полезные фразы для поездки.',
      'wiki_info3': 'Где вы находитесь? Выберите место назначения.',
      'wiki_info4': 'Туристическое место',
      'wiki_des1': 'Остров, известный пляжами, храмами и живой культурой.',
      'wiki_des2': 'Культурное сердце Явы и дом храма Боробудур.',
      'wiki_des3': 'Шумная столица, сочетающая культуру, бизнес и историю.',
      'wiki_des4': 'Одна из самых красивых морских жемчужин в мире',
      'wiki_info5': 'Общие советы путешественникам по Индонезии',
      'wiki_info6': 'Важные советы для всех туристов',
      'wiki_drop1': '• Выучите базовые индонезийские фразы – местные оценят ваши усилия',
      'wiki_drop2': '• Одевайтесь скромно, особенно при посещении религиозных мест',
      'wiki_drop3': '• Всегда носите мелкие деньги (рупии) для местных транзакций',
      'wiki_drop4': '• Скачайте офлайн-карты перед поездкой в удаленные районы',
      'wiki_drop5': '• Попробуйте местную уличную еду в оживленных лавках (большой оборот = свежая еда)',
      'wiki_drop6': '• Торгуйтесь на рынках и с уличными продавцами',
      'wiki_drop7': '• Используйте официальное такси или приложения (Gojek, Grab)',
      'wiki_drop8': '• Храните копии важных документов отдельно',
      'wiki_drop9': '• Приобретите туристическую страховку до поездки',
      'wiki_drop10': '• Уважайте местные обычаи и религиозные практики',
      'wiki_info7': 'Экстренные номера в Индонезии',
      'wiki_info8': 'Сохраните эти номера перед поездкой',
      'wiki_em1': 'Полиция: 110',
      'wiki_em2': 'Скорая помощь: 118',
      'wiki_em3': 'Пожарная служба: 113',
      'wiki_all_destinations': 'Все направления',
      'wiki_back': 'Назад',
      'wiki_about_label': 'Об {title}',
      'wiki_tab_attractions': 'Достопримечательности',
      'wiki_tab_culture': 'Культура & Фразы',
      'wiki_tab_emergency': 'Экстренное',
      'wiki_top_locations': 'Топ места',
      'wiki_cultural_highlights': 'Культура',
      'wiki_emergency_numbers': 'Номера',

      // destinations
      'bali': 'Бали',
      'yogyakarta': 'Джокьякарта',
      'jakarta': 'Джакарта',
      'raja_ampat': 'Раджа-Ампат',

      // wiki content - bali attractions
      'bali_att_1': 'Пляж Кута',
      'bali_att_1_tip1': 'Идеальное место для закатных фото',
      'bali_att_1_tip2': 'Популярно среди начинающих серферов',
      'bali_att_1_tip3': 'Рядом кафе и рестораны',
      'bali_att_1_tip4': 'Легко добраться на скутере или автомобиле',
      'bali_att_2': 'Храм Улувату',
      'bali_att_2_tip1': 'Знаменитый храм на скале с видом на океан',
      'bali_att_2_tip2': 'Культурный танец Кечак на закате',
      'bali_att_2_tip3': 'Отличное место для фотографии',
      'bali_att_2_tip4': 'Осторожно с обезьянами!',
      'bali_att_3': 'Пляж Семиньяк',
      'bali_att_3_tip1': 'Модный пляж с кафе и барами',
      'bali_att_3_tip2': 'Отличное место для наблюдения заката',
      'bali_att_3_tip3': 'Доступны водные виды спорта',
      'bali_att_3_tip4': 'Оживлённая атмосфера',

      // wiki content - bali cultures
      'bali_cul_1': 'Балийский танец',
      'bali_cul_1_det1': 'Традиционное выступление танца Кечак',
      'bali_cul_1_det2': 'Исполняется в храмах во время церемоний',
      'bali_cul_1_det3': 'Повествование через музыку и движение',
      'bali_cul_1_det4': 'Популярный культурный опыт для туристов',
      'bali_cul_2': 'Местная кухня',
      'bali_cul_2_det1': 'Попробуйте Бabi Гулинг (жареный поросёнок) и Лавар',
      'bali_cul_2_det2': 'Яркая сцена уличной еды',
      'bali_cul_2_det3': 'Свежие продукты с местных рынков',
      'bali_cul_2_det4': 'Острые и ароматные блюда',
      'bali_cul_3': 'Полезные фразы',
      'bali_cul_3_det1': 'Om Swastiastu — Балийское приветствие',
      'bali_cul_3_det2': 'Suksma — Спасибо',
      'bali_cul_3_det3': 'Rahajeng semeng — Доброе утро',
      'bali_cul_3_det4': 'Ampura — Извините / Прошу прощения',

      // wiki content - yogyakarta attractions
      'yogy_att_1': 'Храм Боробудур',
      'yogy_att_1_tip1': 'Самый большой буддийский храм в мире',
      'yogy_att_1_tip2': 'Лучше всего посещать на рассвете',
      'yogy_att_1_tip3': 'Одевайтесь скромно',
      'yogy_att_1_tip4': 'Объект Всемирного наследия ЮНЕСКО',
      'yogy_att_2': 'Храм Прамбанан',
      'yogy_att_2_tip1': 'Потрясающий индуистский храмовый комплекс',
      'yogy_att_2_tip2': 'Ночное световое шоу доступно',
      'yogy_att_2_tip3': 'Рядом с Боробудуром — отличная комбинация',
      'yogy_att_2_tip4': 'Красиво в золотой час',
      'yogy_att_3': 'Кратон Джокьякарта',
      'yogy_att_3_tip1': 'Королевский дворец Султана',
      'yogy_att_3_tip2': 'Культурные выступления по выходным',
      'yogy_att_3_tip3': 'Доступны экскурсии с гидом',
      'yogy_att_3_tip4': 'Богатая история яванских королей',

      // wiki content - yogyakarta cultures
      'yogy_cul_1': 'Ваянг Кулит',
      'yogy_cul_1_det1': 'Традиционное шоу теневых марионеток',
      'yogy_cul_1_det2': 'Исполняется всю ночь во время церемоний',
      'yogy_cul_1_det3': 'Истории из индуистских эпосов (Рамаяна, Махабхарата)',
      'yogy_cul_1_det4': 'Нематериальное культурное наследие ЮНЕСКО',
      'yogy_cul_2': 'Батик',
      'yogy_cul_2_det1': 'Искусство, признанное ЮНЕСКО',
      'yogy_cul_2_det2': 'Попробуйте создать свой батик на мастер-классах',
      'yogy_cul_2_det3': 'Маliоборо — лучшее место для покупки',
      'yogy_cul_2_det4': 'Узоры несут культурные смыслы',
      'yogy_cul_3': 'Полезные фразы',
      'yogy_cul_3_det1': 'Sugeng rawuh — Добро пожаловать (яванский)',
      'yogy_cul_3_det2': 'Matur nuwun — Спасибо (яванский)',
      'yogy_cul_3_det3': 'Mangga — Пожалуйста / Прошу',
      'yogy_cul_3_det4': 'Nuwun sewu — Извините',

      // wiki content - jakarta attractions
      'jak_att_1': 'Старый город (Кота Туа)',
      'jak_att_1_tip1': 'Голландская колониальная архитектура',
      'jak_att_1_tip2': 'Рядом музей Фатахиллах',
      'jak_att_1_tip3': 'Уличная еда вокруг площади',
      'jak_att_1_tip4': 'Отлично для любителей истории',
      'jak_att_2': 'Тысяча островов',
      'jak_att_2_tip1': 'Островной отдых вдали от города',
      'jak_att_2_tip2': 'Места для снорклинга и дайвинга',
      'jak_att_2_tip3': '1–2 часа на лодке от Муара Ангке',
      'jak_att_2_tip4': 'Лучше посещать в будние дни',
      'jak_att_3': 'Таман Мини Индонезия Индах',
      'jak_att_3_tip1': 'Культурный парк со всеми провинциями',
      'jak_att_3_tip2': 'Семейное направление',
      'jak_att_3_tip3': 'Большая территория — лучше на транспорте',
      'jak_att_3_tip4': 'Традиционные дома из каждого региона',

      // wiki content - jakarta cultures
      'jak_cul_1': 'Культура Бетави',
      'jak_cul_1_det1': 'Коренная культура Джакарты',
      'jak_cul_1_det2': 'Танец с куклами-гигантами Ондел-ондел',
      'jak_cul_1_det3': 'Керак Телор: традиционная закуска из клейкого риса',
      'jak_cul_1_det4': 'Ленонг: комедийный народный театр',
      'jak_cul_2': 'Современная гастрономия',
      'jak_cul_2_det1': 'Уличная еда в Глодоке (Чайнатаун)',
      'jak_cul_2_det2': 'Гадо-гадо и Сото Бетави обязательны к попробованию',
      'jak_cul_2_det3': 'Много международной кухни',
      'jak_cul_2_det4': 'Фуд-корты в торговых центрах доступны по цене',
      'jak_cul_3': 'Полезные фразы',
      'jak_cul_3_det1': 'Halo / Hai — Привет',
      'jak_cul_3_det2': 'Terima kasih — Спасибо',
      'jak_cul_3_det3': 'Maaf — Извините / Прошу прощения',
      'jak_cul_3_det4': 'Berapa harganya? — Сколько стоит?',

      // wiki content - raja ampat attractions
      'ra_att_1': 'Острова Ваяг',
      'ra_att_1_tip1': 'Иконический вид на карстовые острова',
      'ra_att_1_tip2': 'Лучше добираться на скоростном катере',
      'ra_att_1_tip3': 'Фототочка на рассвете',
      'ra_att_1_tip4': 'Один из красивейших видов Индонезии',
      'ra_att_2': 'Пианемо',
      'ra_att_2_tip1': 'Смотровая площадка над бирюзовой лагуной',
      'ra_att_2_tip2': 'Требует короткого похода',
      'ra_att_2_tip3': 'Каждый шаг стоит этого вида',
      'ra_att_2_tip4': 'Отличный снорклинг у подножия',
      'ra_att_3': 'Деревня Арборек',
      'ra_att_3_tip1': 'Традиционная папуасская рыбацкая деревня',
      'ra_att_3_tip2': 'Снорклинг прямо с причала',
      'ra_att_3_tip3': 'Поддержите местные промыслы',
      'ra_att_3_tip4': 'Тёплое и гостеприимное сообщество',

      // wiki content - raja ampat cultures
      'ra_cul_1': 'Папуасские традиции',
      'ra_cul_1_det1': 'Традиционные танцы в костюмах из перьев и ракушек',
      'ra_cul_1_det2': 'Богатая устная история и племенная культура',
      'ra_cul_1_det3': 'Уважайте местные обычаи при посещении деревень',
      'ra_cul_1_det4': 'Спрашивайте разрешения перед фотографированием',
      'ra_cul_2': 'Местная еда',
      'ra_cul_2_det1': 'Свежие морепродукты ежедневного улова',
      'ra_cul_2_det2': 'Папеда (саговая каша) с рыбным супом',
      'ra_cul_2_det3': 'Уникальные вкусы восточной Индонезии',
      'ra_cul_2_det4': 'Пинанг (бетель) часто жуют местные жители',
      'ra_cul_3': 'Полезные фразы',
      'ra_cul_3_det1': 'Selamat datang — Добро пожаловать',
      'ra_cul_3_det2': 'Terima kasih — Спасибо',
      'ra_cul_3_det3': 'Permisi — Извините',
      'ra_cul_3_det4': 'Tolong — Пожалуйста / Помогите',

      // quiz screen
      'quiz_title': 'Тест',
      'quiz_soal_progress': 'Вопрос {current} / {total}',
      'quiz_hint': 'Напишите или запишите ответ...',
      'quiz_ref_answer': 'Правильный ответ:',
      'quiz_similarity': 'Схожесть:',
      'quiz_submit': 'Отправить Ответ',
      'quiz_fill_first': 'Пожалуйста, сначала введите ответ.',
      'quiz_analyzing': 'Ваш ответ анализируется...',
      'quiz_finished': 'Тест Завершён!',
      'quiz_final_score': 'Ваш Итоговый Результат:',
      'quiz_correct_count': 'Правильно {correct} из {total} вопросов',
      'quiz_score_saved': 'Ваш результат автоматически сохранён в реальном времени.',
      'quiz_back_menu': 'Вернуться в Меню',
      'quiz_status': 'Статус:',
      'quiz_reason_label': 'Причина:',
      'quiz_next': 'Следующий Вопрос',
      'quiz_done': 'Завершить',
      'quiz_load_fail': 'Не удалось загрузить вопросы. Попробуйте снова.',
      'quiz_retry': 'Попробовать Снова',
      'quiz_no_questions': 'Вопросы недоступны.',
      'status_correct': 'Правильно',
      'status_partial': 'Почти правильно',
      'status_incorrect': 'Неправильно',
      'evaluated_by_gemini': 'Оценено Gemini',

      //Learning template
      'l_hint1': 'Сценарий завершён!',
      'l_hint2': 'Вы завершили все уроки. Готовы к тесту?',
      'l_completed': '{percent}% завершено',
      'l_quiz_button': 'Начать тест',
      'listening_top': 'Прослушайте следующую аудиозапись',
      'listening_sub': 'Слушайте внимательно и переходите к следующему вопросу',
      'writing_top': 'Напишите ваш ответ',
      'writing_sub': 'Переведите следующее предложение на индонезийский язык',
      'speaking_top': 'Произнесите вслух',
      'speaking_sub': 'Прочитайте предложение чётко',
      'question_title': 'Вопрос {current} из {total}',
      'l_hint_writting': 'Введите ваш ответ на индонезийском языке.',
      'l_send': 'Отправить',
      'answer_empty': 'Пожалуйста, сначала введите ваш ответ.',
      'answer_wrong': '❌ Неправильный ответ.\n\nПодсказка: Попробуйте написать "{correct}"',
      'answer_correct': '✅ Правильно! Сходство: {score}%',
      'listening_status': 'Прослушивание...',
      'mic_hint': 'Нажмите на микрофон и говорите...',
      'send_voice': 'Отправить голос',
      'speaking_wrong': '❌ Неправильно. Вы сказали: "{spoken}".\n\nПодсказка: Попробуйте сказать "{correct}"',
      'all_done': 'Все вопросы выполнены!',
      'l_next': 'Далее',
      'beginner': 'Начинающий',
      'intermediate': 'Средний',
      'advanced': 'Продвинутый',
      'expert': 'Эксперт',
      'questions_not_available': 'Вопросы недоступны',
      'error_try_again': 'Что-то пошло не так, пожалуйста, попробуйте еще раз.',
      'learning_tab_listening': 'Аудирование',
      'learning_tab_writing': 'Письмо',
      'learning_tab_speaking': 'Говорение',

      // auth
      'login_title': 'Wicara Wisata',
      'signin_tab': 'Войти',
      'signup_tab': 'Регистрация',
      'email_label': 'Почта',
      'password_label': 'Пароль',
      'username_label': 'Имя пользователя',
      'forgot_password_link': 'Забыли пароль?',
      'signin_button': 'Войти',
      'signup_button': 'Регистрация',
      'create_account_button': 'Создать аккаунт',
      'continue_with_google': 'Войти через Google',
      'or_divider': 'ИЛИ',
      'auth_error_filling': 'Все поля обязательны',
      'reset_password_title': 'Сброс пароля',
      'reset_password_desc': 'Введите email для получения ссылки.',
      'send_reset_link_button': 'Отправить ссылку',
      'back_to_login': 'Назад к входу',
      'email_sent_title': 'Отправлено!',
      'email_sent_desc': 'Ссылка для сброса отправлена на:',
      'check_inbox_spam': 'Проверьте почту и папку спам.',

      // home additions
      'home_keep_it_up': '🔥 Так держать!',
      'home_progress_of_lessons': '{current} из {total} уроков',
      'home_user_not_found': 'Данные не найдены',
      'home_active_course': 'Активный курс',
      'home_currently_working_on': 'Текущий курс',
      'home_completed_label': '{percent}% завершено',

      // levels
      'select_your_level': '🎓 Выберите уровень',
      'level_beginner': 'Начальный',
      'level_intermediate': 'Средний',
      'level_advanced': 'Продвинутый',

      // settings additions
      'logout_button': 'Выйти',
      'logout_confirm_title': 'Выход',
      'logout_confirm_content': 'Вы уверены, что хотите выйти?',
      'cancel_button': 'Отмена',
      'changes_saved_msg': 'Сохранено!',
      'admin_tools_title': 'Админ',
      'admin_upload_button': 'Загрузка данных',
      'no_scenarios_for_level': 'Нет доступных сценариев для уровня {level}.',
    },

    'zh': {
      // settings
      'settings_title': '设置',
      'set_info': '管理您的账户偏好',
      'profile_info': '个人信息',
      'update_details': '更新您的个人信息',
      'name': '姓名',
      'email': '电子邮箱',
      'email_cannot_change': '电子邮箱无法更改',
      'language_pref': '语言偏好',
      'choose_language': '选择您的语言',
      'recent_language': '当前语言：',
      'save_changes': '保存更改',
      'note_language_change': '注意：\n更改语言将应用于所有课程。',

      // home screens
      'welcome_user': '欢迎，{name}',
      'info_home_1': '总体进度',
      'quiz_info_1': '测验表现',
      'info_home_2': '开始您的旅程',
      'info_home_3': '今天开始学习印尼语',
      'info_home_4': '从18节课程中选择，涵盖3个难度等级。',
      'info_home_5': '学习机场、酒店、餐厅、购物、交通和医疗场景中的常用短语。',
      'info_home_6': '交通和医疗相关内容。',
      'button_learn': '开始学习',
      'info_home_7': '探索印度尼西亚',
      'info_home_8': '热门目的地',
      'info_home_9': '旅行小贴士',
      'info_home_10': '紧急用语',
      'info_home_11': '探索百科',

      // levels
      'level_info': '选择你的级别',
      'level_info_2': '选择难度级别开始你的旅程',
      'lvl1': '初级',
      'lvl1_sub': '基础日常对话',
      'lvl2': '中级',
      'lvl2_sub': '进阶日常对话',
      'lvl3': '高级',
      'lvl3_sub': '复杂交流',
      'lvl_button': '开始学习',

      // scenario
      'airport': '机场',
      'airport_desc': '学习机场常用短语和技巧。',
      'hotel': '酒店',
      'hotel_desc': '酒店住宿常用句子。',
      'restaurant': '餐厅',
      'restaurant_desc': '餐饮短语和词汇。',
      'shopping': '购物',
      'shopping_desc': '购物用词和技巧。',
      'market': '市场',
      'market_desc': '传统市场的基本短语。',
      'transportation': '交通',
      'transportation_desc': '出行常用短语。',
      'hospital': '医院',
      'hospital_desc': '医疗和紧急短语。',
      'clinic': '诊所',
      'clinic_desc': '医疗方案和治疗短语。',
      'start_learning': '开始学习',

      // wiki
      'wiki_info1': '印度尼西亚旅游百科',
      'wiki_info2': '探索印度尼西亚的著名景点，并学习旅行中有用的短语。',
      'wiki_info3': '你在哪里？选择你的目的地。',
      'wiki_info4': '旅游目的地',
      'wiki_des1': '以海滩、寺庙和多彩文化闻名的岛屿。',
      'wiki_des2': '爪哇文化中心，婆罗浮屠寺的所在地。',
      'wiki_des3': '融合文化、商业和历史的繁忙首都。',
      'wiki_des4': '世界上最美丽的海洋天堂之一',
      'wiki_info5': '印尼旅行通用建议',
      'wiki_info6': '所有旅行者的重要提示',
      'wiki_drop1': '• 学习基础印尼语短语——当地人会欣赏你的努力',
      'wiki_drop2': '• 穿着得体，尤其是参观宗教场所时',
      'wiki_drop3': '• 始终携带小额纸币（卢比）进行当地交易',
      'wiki_drop4': '• 前往偏远地区前下载离线地图',
      'wiki_drop5': '• 尝试繁忙摊位的当地街头美食（周转快 = 食材新鲜）',
      'wiki_drop6': '• 在市场和街头小贩处讨价还价',
      'wiki_drop7': '• 使用官方出租车或叫车应用（Gojek, Grab）',
      'wiki_drop8': '• 将重要文件的副本单独保存',
      'wiki_drop9': '• 出行前购买旅游保险',
      'wiki_drop10': '• 尊重当地习俗和宗教实践',
      'wiki_info7': '印尼紧急号码',
      'wiki_info8': '旅行前保存这些重要号码',
      'wiki_em1': '警察: 110',
      'wiki_em2': '救护车: 118',
      'wiki_em3': '消防: 113',
      'wiki_all_destinations': '所有目的地',
      'wiki_back': '返回',
      'wiki_about_label': '关于 {title}',
      'wiki_tab_attractions': '景点',
      'wiki_tab_culture': '文化 & 短语',
      'wiki_tab_emergency': '紧急情况',
      'wiki_top_locations': '热门地点',
      'wiki_cultural_highlights': '文化亮点',
      'wiki_emergency_numbers': '紧急号码',

      // destinations
      'bali': '巴厘岛',
      'yogyakarta': '日惹',
      'jakarta': '雅加达',
      'raja_ampat': '拉贾安帕特',

      // wiki content - bali attractions
      'bali_att_1': '库塔海滩',
      'bali_att_1_tip1': '欣赏日落和摄影的理想地点',
      'bali_att_1_tip2': '冲浪初学者的热门选择',
      'bali_att_1_tip3': '靠近咖啡馆和餐厅',
      'bali_att_1_tip4': '骑摩托车或开车方便到达',
      'bali_att_2': '乌鲁瓦图寺',
      'bali_att_2_tip1': '著名的海滨悬崖寺庙',
      'bali_att_2_tip2': '日落时的 Kecak 文化舞蹈',
      'bali_att_2_tip3': '绝佳摄影景点',
      'bali_att_2_tip4': '小心猴子！',
      'bali_att_3': '水明漾海滩',
      'bali_att_3_tip1': '时尚海滩，周边有咖啡馆和酒吧',
      'bali_att_3_tip2': '观赏日落的好地方',
      'bali_att_3_tip3': '水上运动项目丰富',
      'bali_att_3_tip4': '热闹活跃的氛围',

      // wiki content - bali cultures
      'bali_cul_1': '巴厘岛舞蹈',
      'bali_cul_1_det1': '传统 Kecak 舞蹈表演',
      'bali_cul_1_det2': '在寺庙仪式中演出',
      'bali_cul_1_det3': '通过音乐与动作讲述故事',
      'bali_cul_1_det4': '深受游客喜爱的文化体验',
      'bali_cul_2': '当地美食',
      'bali_cul_2_det1': '推荐尝试 Babi Guling（烤乳猪）和 Lawar',
      'bali_cul_2_det2': '充满活力的街头小吃文化',
      'bali_cul_2_det3': '来自当地市场的新鲜食材',
      'bali_cul_2_det4': '香辣美味的菜肴',
      'bali_cul_3': '实用短语',
      'bali_cul_3_det1': 'Om Swastiastu — 巴厘岛问候语',
      'bali_cul_3_det2': 'Suksma — 谢谢',
      'bali_cul_3_det3': 'Rahajeng semeng — 早上好',
      'bali_cul_3_det4': 'Ampura — 对不起 / 打扰一下',

      // wiki content - yogyakarta attractions
      'yogy_att_1': '婆罗浮屠寺',
      'yogy_att_1_tip1': '世界上最大的佛教寺庙',
      'yogy_att_1_tip2': '建议日出时参观',
      'yogy_att_1_tip3': '请着装得体',
      'yogy_att_1_tip4': '联合国教科文组织世界遗产',
      'yogy_att_2': '普兰巴南寺',
      'yogy_att_2_tip1': '令人惊叹的印度教寺庙群',
      'yogy_att_2_tip2': '夜间灯光秀可选',
      'yogy_att_2_tip3': '靠近婆罗浮屠，适合组合游览',
      'yogy_att_2_tip4': '黄金时刻景色迷人',
      'yogy_att_3': '日惹王宫',
      'yogy_att_3_tip1': '苏丹王室宫殿',
      'yogy_att_3_tip2': '周末有文化表演',
      'yogy_att_3_tip3': '提供导览服务',
      'yogy_att_3_tip4': '爪哇皇室的丰富历史',

      // wiki content - yogyakarta cultures
      'yogy_cul_1': '皮影戏 (Wayang Kulit)',
      'yogy_cul_1_det1': '传统皮影戏表演',
      'yogy_cul_1_det2': '在仪式中通宵演出',
      'yogy_cul_1_det3': '讲述印度史诗故事（罗摩衍那、摩诃婆罗多）',
      'yogy_cul_1_det4': '联合国教科文组织非物质文化遗产',
      'yogy_cul_2': '蜡染工艺',
      'yogy_cul_2_det1': '联合国教科文组织认可的艺术形式',
      'yogy_cul_2_det2': '可在工坊亲自制作蜡染',
      'yogy_cul_2_det3': 'Malioboro 是购买蜡染的最佳地点',
      'yogy_cul_2_det4': '图案蕴含文化含义',
      'yogy_cul_3': '实用短语',
      'yogy_cul_3_det1': 'Sugeng rawuh — 欢迎（爪哇语）',
      'yogy_cul_3_det2': 'Matur nuwun — 谢谢（爪哇语）',
      'yogy_cul_3_det3': 'Mangga — 请 / 请便',
      'yogy_cul_3_det4': 'Nuwun sewu — 打扰一下',

      // wiki content - jakarta attractions
      'jak_att_1': '老城区 (Kota Tua)',
      'jak_att_1_tip1': '荷兰殖民时期建筑',
      'jak_att_1_tip2': '附近有法塔希拉博物馆',
      'jak_att_1_tip3': '广场周围有街边小吃',
      'jak_att_1_tip4': '历史爱好者的好去处',
      'jak_att_2': '千岛群岛',
      'jak_att_2_tip1': '远离城市喧嚣的岛屿假期',
      'jak_att_2_tip2': '浮潜和潜水胜地',
      'jak_att_2_tip3': '从 Muara Angke 乘船约 1–2 小时',
      'jak_att_2_tip4': '建议工作日前往',
      'jak_att_3': '印尼美化公园',
      'jak_att_3_tip1': '展示所有省份的文化公园',
      'jak_att_3_tip2': '适合家庭出游',
      'jak_att_3_tip3': '面积广阔，建议乘车游览',
      'jak_att_3_tip4': '每个地区的传统民居',

      // wiki content - jakarta cultures
      'jak_cul_1': '巴达维文化',
      'jak_cul_1_det1': '雅加达本土文化',
      'jak_cul_1_det2': 'Ondel-ondel 巨型木偶舞',
      'jak_cul_1_det3': 'Kerak Telor：传统糯米小吃',
      'jak_cul_1_det4': 'Lenong：喜剧民间戏剧',
      'jak_cul_2': '现代美食场景',
      'jak_cul_2_det1': 'Glodok（唐人街）街头美食',
      'jak_cul_2_det2': '必尝 Gado-gado 和 Soto Betawi',
      'jak_cul_2_det3': '国际美食种类丰富',
      'jak_cul_2_det4': '商场美食广场价格实惠',
      'jak_cul_3': '实用短语',
      'jak_cul_3_det1': 'Halo / Hai — 你好',
      'jak_cul_3_det2': 'Terima kasih — 谢谢',
      'jak_cul_3_det3': 'Maaf — 对不起 / 打扰一下',
      'jak_cul_3_det4': 'Berapa harganya? — 多少钱？',

      // wiki content - raja ampat attractions
      'ra_att_1': '瓦亚格群岛',
      'ra_att_1_tip1': '标志性的喀斯特岛屿景色',
      'ra_att_1_tip2': '建议乘坐快艇前往',
      'ra_att_1_tip3': '日出时的绝佳摄影地点',
      'ra_att_1_tip4': '印度尼西亚最美丽的景观之一',
      'ra_att_2': '皮亚内莫',
      'ra_att_2_tip1': '俯瞰碧绿泻湖的观景台',
      'ra_att_2_tip2': '需要短途徒步',
      'ra_att_2_tip3': '美景值得每一步',
      'ra_att_2_tip4': '观景台下方浮潜体验极佳',
      'ra_att_3': '阿博雷克村',
      'ra_att_3_tip1': '传统的巴布亚渔村',
      'ra_att_3_tip2': '可直接从码头浮潜',
      'ra_att_3_tip3': '支持当地手工艺品',
      'ra_att_3_tip4': '热情好客的社区',

      // wiki content - raja ampat cultures
      'ra_cul_1': '巴布亚传统',
      'ra_cul_1_det1': '穿着羽毛和贝壳服饰的传统舞蹈',
      'ra_cul_1_det2': '丰富的口头历史和部落文化',
      'ra_cul_1_det3': '参观村庄时请尊重当地习俗',
      'ra_cul_1_det4': '拍照前请征得当地人同意',
      'ra_cul_2': '当地饮食',
      'ra_cul_2_det1': '每日新鲜捕获的海鲜',
      'ra_cul_2_det2': 'Papeda（西米粥）配鱼汤',
      'ra_cul_2_det3': '来自印尼东部的独特风味',
      'ra_cul_2_det4': '槟榔在当地是常见的咀嚼物',
      'ra_cul_3': '实用短语',
      'ra_cul_3_det1': 'Selamat datang — 欢迎',
      'ra_cul_3_det2': 'Terima kasih — 谢谢',
      'ra_cul_3_det3': 'Permisi — 打扰一下',
      'ra_cul_3_det4': 'Tolong — 请 / 帮助',

      // quiz screen
      'quiz_title': '测验',
      'quiz_soal_progress': '第 {current} / {total} 题',
      'quiz_hint': '写下或录制您的答案...',
      'quiz_ref_answer': '参考答案：',
      'quiz_similarity': '相似度：',
      'quiz_submit': '提交答案',
      'quiz_fill_first': '请先填写您的答案。',
      'quiz_analyzing': '正在分析您的答案...',
      'quiz_finished': '测验完成！',
      'quiz_final_score': '您的最终得分：',
      'quiz_correct_count': '{total} 题中答对 {correct} 题',
      'quiz_score_saved': '您的成绩已实时自动保存。',
      'quiz_back_menu': '返回菜单',
      'quiz_status': '状态：',
      'quiz_reason_label': '原因：',
      'quiz_next': '下一题',
      'quiz_done': '完成',
      'quiz_load_fail': '加载题目失败，请重试。',
      'quiz_retry': '重试',
      'quiz_no_questions': '暂无题目。',
      'status_correct': '正确',
      'status_partial': '几乎正确',
      'status_incorrect': '错误',
      'evaluated_by_gemini': '由 Gemini 评估',

      //Learning template
      'l_hint1': '场景已完成！',
      'l_hint2': '你已完成所有课程，准备好参加测验了吗？',
      'l_completed': '{percent}% 已完成',
      'l_quiz_button': '开始测验',
      'listening_top': '请听以下音频',
      'listening_sub': '请仔细听，然后继续下一题',
      'writing_top': '写下你的答案',
      'writing_sub': '将以下句子翻译成印度尼西亚语',
      'speaking_top': '大声说出来',
      'speaking_sub': '请清晰地朗读这个句子',
      'question_title': '第 {current} 题，共 {total} 题',
      'l_hint_writting': '请用印度尼西亚语输入你的答案。',
      'l_send': '提交',
      'answer_empty': '请先填写你的答案。',
      'answer_wrong': '❌ 答案错误。\n\n提示：试着写 "{correct}"',
      'answer_correct': '✅ 正确！相似度：{score}%',
      'listening_status': '正在收听...',
      'mic_hint': '点击麦克风并说话...',
      'send_voice': '发送语音',
      'speaking_wrong': '❌ 错误。你说的是："{spoken}"。\n\n提示：试着说 "{correct}"',
      'all_done': '所有问题已完成！',
      'l_next': '下一个',
      'beginner': '初学者',
      'intermediate': '中级',
      'advanced': '高级',
      'expert': '专家',
      'questions_not_available': '暂无题目',
      'error_try_again': '出错了，请稍后再试。',
      'learning_tab_listening': '听力',
      'learning_tab_writing': '写作',
      'learning_tab_speaking': '口语',

      // auth
      'login_title': 'Wicara Wisata',
      'signin_tab': '登录',
      'signup_tab': '注册',
      'email_label': '电子邮箱',
      'password_label': '密码',
      'username_label': '用户名',
      'forgot_password_link': '忘记密码？',
      'signin_button': '登录',
      'signup_button': '注册',
      'create_account_button': '创建账户',
      'continue_with_google': '使用 Google 继续',
      'or_divider': '或',
      'auth_error_filling': '所有字段均为必填',
      'reset_password_title': '重置密码',
      'reset_password_desc': '输入您的邮箱，我们将发送重置链接。',
      'send_reset_link_button': '发送链接',
      'back_to_login': '返回登录',
      'email_sent_title': '邮件已发送！',
      'email_sent_desc': '重置链接已发送至：',
      'check_inbox_spam': '请检查收件箱和垃圾邮件文件夹。',

      // home additions
      'home_keep_it_up': '🔥 继续加油！',
      'home_progress_of_lessons': '{current} / {total} 课',
      'home_user_not_found': '未找到用户数据',
      'home_active_course': '当前课程',
      'home_currently_working_on': '正在学习',
      'home_completed_label': '{percent}% 已完成',

      // levels
      'select_your_level': '🎓 选择您的级别',
      'level_beginner': '初级',
      'level_intermediate': '中级',
      'level_advanced': '高级',

      // settings additions
      'logout_button': '退出',
      'logout_confirm_title': '登出',
      'logout_confirm_content': '您确定要退出吗？',
      'cancel_button': '取消',
      'changes_saved_msg': '更改已保存！',
      'admin_tools_title': '管理员工具',
      'admin_upload_button': '打开数据上传器',
      'no_scenarios_for_level': '{level} 级别暂无场景。',
    },
  };

  String t(String key, {Map<String, String>? params}) {
    String text = translations[_currentLang]?[key] ?? key;

    if (params != null) {
      params.forEach((k, v) {
        text = text.replaceAll('{$k}', v);
      });
    }

    return text;
  }

  Future<void> changeLanguage(String lang) async {
    _currentLang = lang;
    notifyListeners();

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('lang', lang);
  }

  Future<void> loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLang = prefs.getString('lang') ?? 'en';
  }
}