import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  String _currentLang = 'en';

  String get currentLang => _currentLang;

  final Map<String, Map<String, String>> translations = {
    'en': {
      //settings
      'settings_title': 'Settings',
      'set_info': 'Manage your account preferences',
      'profile_info': 'Profile Information',
      'update_details': 'Update your personal details',
      'name': 'Name',
      'email': 'Email',
      'email_cannot_change': 'Email cannot be changed',
      'language_pref': 'Language Preferences',
      'choose_language': 'Choose your language',
      'recent_language': 'Recent Language:',
      'save_changes': 'Save Changes',
      'note_language_change': 'Note:\nChanging your language will apply to all lessons.',

      //home screens
      'welcome_user': 'Welcome, {name}',
      'info_home_1': 'Overall Progress',
      'quiz_info_1': 'Quiz Performance',
      'info_home_2': 'Start your journey',
      'info_home_3': 'Begin Learing Indonesian Today',
      'info_home_4': 'Choose from 18 lessons across 3 difficulty levels.',
      'info_home_5': 'Learn essential phrases for airports, hotels, restaurants, shopping, transportation, and medical facilities.',
      'info_home_6': 'transportation, and medical facilities.',
      'button_learn': 'Start Learning',
      'info_home_7': 'Explore Indonesia',
      'info_home_8': 'Popular destination',
      'info_home_9': 'Travel Tips',
      'info_home_10': 'Emergency phrases',
      'info_home_11': 'Explore Wiki',

      // levels
      'level_info': 'Choose your level',
      'level_info_2' : 'Select a difficulty level to begin your journey',
      'lvl1': 'Beginner',
      'lvl1_sub' : 'Basic daily conversation',
      'lvl2': 'Intermediate',
      'lvl2_sub': 'Advanced daily conversation',
      'lvl3': 'Expert',
      'lvl3_sub': 'Complex communication',
      'lvl_button': 'Start Learning',

      //scenario
      'airport': 'Airport',
      'airport_desc': 'Learn airport phrases and tips.',
      'hotel': 'Hotel',
      'hotel_desc': 'Useful sentences for hotel stays.',
      'restaurant': 'Restaurant',
      'restaurant_desc': 'Dining phrases and vocabulary.',
      'shopping': 'Shopping',
      'shopping_desc': 'Words and tips for shopping.',
      'market': 'Market',
      'market_desc': 'Essential phrases for traditional markets.',
      'transportation': 'Transportation',
      'transportation_desc': 'Get around using transport phrases.',
      'hospital': 'Hospital',
      'hospital_desc': 'Healthcare and emergency phrases.',
      'clinic': 'Clinic',
      'clinic_desc': 'Medical scenario and treatment phrases.',
      'start_learning': 'Start Learning',

      //wiki
      'wiki_info1': 'Indonesia Tourist Wiki',
      'wiki_info2': 'Explore famous destinations across Indonesia and learn useful phrases for your trip.',
      'wiki_info3': 'Where you are?. Select your destination.',
      'wiki_info4': 'Tourist Destination.',
      "wiki_des1": 'Island famous for beaches, temples, and vibrant culture.',
      "wiki_des2": 'Cultural heart of Java and home of Borobudur temple.',
      "wiki_des3": 'Bustling capital city blending culture, business and history.',
      "wiki_des4": 'One of the most beautiful marine paradises in the world',
      'wiki_info5': 'General Travel Tips for Indonesia',
      'wiki_info6': 'Essential Tips for All Travelers',
      'wiki_drop1': '• Learn basic Indonesian phrases - locals appreciate the effort',
      'wiki_drop2': '• Dress modestly, especially when visiting religious sites',
      'wiki_drop3': '• Always carry small bills (Rupiah) for local transactions',
      'wiki_drop4': '• Download offline maps before traveling to remote areas',
      'wiki_drop5': '• Try local street food from busy stalls (high turnover = fresh food)',
      'wiki_drop6': '• Negotiate prices at markets and with street vendors',
      'wiki_drop7': '• Use official taxis or ride-hailing apps (Gojek, Grab)',
      'wiki_drop8': '• Keep copies of important documents separately',
      'wiki_drop9': '• Purchase travel insurance before your trip',
      'wiki_drop10': '• Respect local customs and religious practices',
      'wiki_info7': 'Emergency Numbers in Indonesia',
      'wiki_info8': 'Save these important numbers before traveling',
      'wiki_em1': 'Police: 110',
      'wiki_em2': 'Ambulance: 118',
      'wiki_em3': 'Fire Department: 113',

      // quiz screen
      'quiz_title': 'Quiz',
      'quiz_soal_progress': 'Question {current} / {total}',
      'quiz_hint': 'Write or record your answer...',
      'quiz_ref_answer': 'Reference answer:',
      'quiz_similarity': 'Similarity:',
      'quiz_submit': 'Submit Answer',
      'quiz_fill_first': 'Please fill in your answer first.',
      'quiz_analyzing': 'Your answer is being analyzed...',
      'quiz_finished': 'Quiz Finished!',
      'quiz_final_score': 'Your Final Score:',
      'quiz_correct_count': 'Correct {correct} out of {total} questions',
      'quiz_score_saved': 'Your score has been automatically saved in real-time.',
      'quiz_back_menu': 'Back to Menu',
      'quiz_status': 'Status:',
      'quiz_reason_label': 'Reason:',
      'quiz_next': 'Next Question',
      'quiz_done': 'Finish',
      'quiz_load_fail': 'Failed to load questions. Please try again.',
      'quiz_retry': 'Try Again',
      'quiz_no_questions': 'No questions available.',
      'status_correct': 'Correct',
      'status_partial': 'Almost Correct',
      'status_incorrect': 'Incorrect',
      'evaluated_by_gemini': 'Evaluated by Gemini',

      //Learning template
      'l_hint1' : 'Scenario Completed!',
      'l_hint2' : 'You finished all lessons. Ready for the quiz?',
      'l_completed': '{percent}% completed',
      'l_quiz_button': 'Start Quiz',
      'listening_top': 'Listen to the following audio',
      'listening_sub': 'Pay attention and continue to the next question',
      'writing_top': 'Write your answer',
      'writing_sub': 'Translate the following sentence into Indonesian',
      'speaking_top': 'Speak out loud',
      'speaking_sub': 'Read the sentence clearly',
      'question_title': 'Question {current} of {total}',
      'l_hint_writting' : 'Type your answer in Indonesian.',
      'l_send' : 'Submit',
      'answer_empty': 'Please fill in your answer first.',
      'answer_wrong': '❌ Incorrect answer.\n\nTip: Try writing "{correct}"',
      'answer_correct': '✅ Correct! Similarity: {score}%',
      'listening_status': 'Listening...',
      'mic_hint': 'Tap the microphone & speak...',
      'send_voice': 'Send Voice',
      'speaking_wrong': '❌ Incorrect. You said: "{spoken}".\n\nTip: Try saying "{correct}"',
      'all_done': 'All questions completed!',
      'l_next' : 'Next',
    },

    'id': {
      //settings
      'settings_title': 'Pengaturan',
      'set_info':'Kelola preferensi akun Anda',
      'profile_info': 'Informasi Profil',
      'update_details': 'Perbarui data pribadi Anda',
      'name': 'Nama',
      'email': 'Email',
      'email_cannot_change': 'Email tidak dapat diubah',
      'language_pref': 'Preferensi Bahasa',
      'choose_language': 'Pilih bahasa Anda',
      'recent_language': 'Bahasa Saat Ini:',
      'save_changes': 'Simpan Perubahan',
      'note_language_change': 'Catatan:\nPerubahan bahasa akan berlaku untuk semua pelajaran.',

      //home screens
      'welcome_user': 'Selamat datang, {name}',
      'info_home_1': 'Progress Keseluruhan',
      'quiz_info_1': 'Performa Kuis',
      'info_home_2': 'Mulai perjalanan Anda',
      'info_home_3': 'Mulai belajar Bahasa Indonesia hari ini',
      'info_home_4': 'Pilih dari 18 pelajaran dalam 3 tingkat kesulitan.',
      'info_home_5': 'Pelajari frasa penting untuk bandara, hotel, restoran, belanja, transportasi, dan fasilitas medis.',
      'info_home_6': 'Transportasi dan fasilitas medis.',
      'button_learn': 'Mulai Belajar',
      'info_home_7': 'Jelajahi Indonesia',
      'info_home_8': 'Destinasi Populer',
      'info_home_9': 'Tips Perjalanan',
      'info_home_10': 'Frasa Darurat',
      'info_home_11': 'Jelajahi Wiki',


      // levels
      'level_info': 'Pilih level Anda',
      'level_info_2': 'Pilih tingkat kesulitan untuk memulai perjalanan Anda',
      'lvl1': 'Pemula',
      'lvl1_sub': 'Percakapan sehari-hari dasar',
      'lvl2': 'Menengah',
      'lvl2_sub': 'Percakapan sehari-hari lanjutan',
      'lvl3': 'Mahir',
      'lvl3_sub': 'Komunikasi kompleks',
      'lvl_button': 'Mulai Belajar',

// scenario
      'airport': 'Bandara',
      'airport_desc': 'Pelajari frasa dan tips di bandara.',
      'hotel': 'Hotel',
      'hotel_desc': 'Kalimat berguna untuk menginap di hotel.',
      'restaurant': 'Restoran',
      'restaurant_desc': 'Frasa dan kosakata makanan.',
      'shopping': 'Belanja',
      'shopping_desc': 'Kata dan tips saat berbelanja.',
      'market': 'Pasar',
      'market_desc': 'Frasa penting untuk belanja di pasar tradisional.',
      'transportation': 'Transportasi',
      'transportation_desc': 'Frasa untuk bepergian.',
      'hospital': 'Rumah Sakit',
      'hospital_desc': 'Frasa kesehatan dan darurat.',
      'clinic': 'Klinik',
      'clinic_desc': 'Skenario kesehatan dan berobat.',
      'start_learning': 'Mulai Belajar',

      'wiki_info1': 'Wiki Wisata Indonesia',
      'wiki_info2': 'Jelajahi destinasi terkenal di Indonesia dan pelajari frasa berguna untuk perjalananmu.',
      'wiki_info3': 'Di mana kamu berada? Pilih tujuanmu.',
      'wiki_info4': 'Destinasi Wisata',
      'wiki_des1': 'Pulau terkenal dengan pantai, candi, dan budaya yang hidup.',
      'wiki_des2': 'Jantung budaya Jawa dan rumah bagi Candi Borobudur.',
      'wiki_des3': 'Ibukota yang ramai memadukan budaya, bisnis, dan sejarah.',
      'wiki_des4': 'Salah satu surga laut paling indah di dunia',
      'wiki_info5': 'Tips Umum Perjalanan di Indonesia',
      'wiki_info6': 'Tips Penting untuk Semua Wisatawan',
      'wiki_drop1': '• Pelajari frasa dasar bahasa Indonesia – penduduk lokal menghargai usaha',
      'wiki_drop2': '• Berpakaian sopan, terutama saat mengunjungi tempat ibadah',
      'wiki_drop3': '• Selalu bawa uang kecil (Rupiah) untuk transaksi lokal',
      'wiki_drop4': '• Unduh peta offline sebelum ke daerah terpencil',
      'wiki_drop5': '• Cicipi makanan jalanan lokal dari warung ramai (lalu-lintas tinggi = makanan segar)',
      'wiki_drop6': '• Tawar-menawar harga di pasar dan dengan pedagang kaki lima',
      'wiki_drop7': '• Gunakan taksi resmi atau aplikasi ojek (Gojek, Grab)',
      'wiki_drop8': '• Simpan salinan dokumen penting secara terpisah',
      'wiki_drop9': '• Beli asuransi perjalanan sebelum perjalanan',
      'wiki_drop10': '• Hormati kebiasaan lokal dan praktik keagamaan',
      'wiki_info7': 'Nomor Darurat di Indonesia',
      'wiki_info8': 'Simpan nomor penting ini sebelum bepergian',
      'wiki_em1': 'Polisi: 110',
      'wiki_em2': 'Ambulans: 118',
      'wiki_em3': 'Pemadam Kebakaran: 113',

      // quiz screen
      'quiz_title': 'Kuis',
      'quiz_soal_progress': 'Soal {current} / {total}',
      'quiz_hint': 'Tulis atau rekam jawaban...',
      'quiz_ref_answer': 'Jawaban referensi:',
      'quiz_similarity': 'Kemiripan:',
      'quiz_submit': 'Kirim Jawaban',
      'quiz_fill_first': 'Silakan isi jawaban dulu.',
      'quiz_analyzing': 'Jawabanmu sedang dianalisis...',
      'quiz_finished': 'Kuis Selesai!',
      'quiz_final_score': 'Nilai Akhir Anda:',
      'quiz_correct_count': 'Benar {correct} dari {total} soal',
      'quiz_score_saved': 'Nilai Anda telah otomatis disimpan secara real-time.',
      'quiz_back_menu': 'Kembali ke Menu',
      'quiz_status': 'Status:',
      'quiz_reason_label': 'Alasan:',
      'quiz_next': 'Soal Berikutnya',
      'quiz_done': 'Selesai',
      'quiz_load_fail': 'Gagal memuat soal. Coba lagi.',
      'quiz_retry': 'Coba Lagi',
      'quiz_no_questions': 'Soal belum tersedia.',
      'status_correct': 'Benar',
      'status_partial': 'Hampir Benar',
      'status_incorrect': 'Kurang Tepat',
      'evaluated_by_gemini': 'Dievaluasi oleh Gemini',

      //Learning template
      'l_hint1' : 'Skenario Selesai!',
      'l_hint2' : 'Kamu menyelesaikan semua pelajaran. Siap untuk kuis?',
      'l_completed': '{percent}% selesai',
      'l_quiz_button': 'Mulai Kuis',
      'listening_top': 'Dengarkan audio berikut',
      'listening_sub': 'Perhatikan baik-baik dan lanjutkan ke pertanyaan berikutnya',
      'writing_top': 'Tulis jawabanmu',
      'writing_sub': 'Terjemahkan kalimat berikut ke dalam bahasa Indonesia',
      'speaking_top': 'Ucapkan dengan keras',
      'speaking_sub': 'Baca kalimat dengan jelas',
      'question_title': 'Pertanyaan {current} dari {total}',
      'l_hint_writting' : 'Ketik jawabanmu dalam bahasa Indonesia.',
      'l_send' : 'Kirim',
      'answer_empty': 'Tolong isi jawabanmu terlebih dahulu.',
      'answer_wrong': '❌ Jawaban salah.\n\nTips: Coba tulis "{correct}"',
      'answer_correct': '✅ Benar! Kemiripan: {score}%',
      'listening_status': 'Sedang mendengarkan...',
      'mic_hint': 'Ketuk mikrofon & bicara...',
      'send_voice': 'Kirim Suara',
      'speaking_wrong': '❌ Salah. Kamu berkata: "{spoken}".\n\nTips: Coba ucapkan "{correct}"',
      'all_done': 'Semua pertanyaan selesai!',
      'l_next' : 'Lanjut',
    },

    'es': {
      // settings
      'settings_title': 'Configuración',
      'set_info': 'Administra las preferencias de tu cuenta',
      'profile_info': 'Información del perfil',
      'update_details': 'Actualiza tus datos personales',
      'name': 'Nombre',
      'email': 'Correo electrónico',
      'email_cannot_change': 'El correo electrónico no se puede cambiar',
      'language_pref': 'Preferencias de idioma',
      'choose_language': 'Elige tu idioma',
      'recent_language': 'Idioma actual:',
      'save_changes': 'Guardar cambios',
      'note_language_change': 'Nota:\nEl cambio de idioma se aplicará a todas las lecciones.',

      // home screens
      'welcome_user': 'Bienvenido, {name}',
      'info_home_1': 'Progreso general',
      'quiz_info_1': 'Rendimiento del cuestionario',
      'info_home_2': 'Comienza tu viaje',
      'info_home_3': 'Empieza a aprender indonesio hoy',
      'info_home_4': 'Elige entre 18 lecciones en 3 niveles de dificultad.',
      'info_home_5': 'Aprende frases esenciales para aeropuertos, hoteles, restaurantes, compras, transporte y servicios médicos.',
      'info_home_6': 'Transporte y servicios médicos.',
      'button_learn': 'Comenzar a aprender',
      'info_home_7': 'Explorar Indonesia',
      'info_home_8': 'Destinos populares',
      'info_home_9': 'Consejos de viaje',
      'info_home_10': 'Frases de emergencia',
      'info_home_11': 'Explorar Wiki',

      // levels
      'level_info': 'Elige tu nivel',
      'level_info_2': 'Selecciona un nivel de dificultad para comenzar tu viaje',
      'lvl1': 'Principiante',
      'lvl1_sub': 'Conversación diaria básica',
      'lvl2': 'Intermedio',
      'lvl2_sub': 'Conversación diaria avanzada',
      'lvl3': 'Experto',
      'lvl3_sub': 'Comunicación compleja',
      'lvl_button': 'Comenzar a aprender',

// scenario
      'airport': 'Aeropuerto',
      'airport_desc': 'Aprende frases y consejos del aeropuerto.',
      'hotel': 'Hotel',
      'hotel_desc': 'Frases útiles para estadías en hotel.',
      'restaurant': 'Restaurante',
      'restaurant_desc': 'Frases y vocabulario de comida.',
      'shopping': 'Compras',
      'shopping_desc': 'Palabras y consejos para comprar.',
      'market': 'Mercado',
      'market_desc': 'Frases esenciales para mercados tradicionales.',
      'transportation': 'Transporte',
      'transportation_desc': 'Frases para moverse.',
      'hospital': 'Hospital',
      'hospital_desc': 'Frases médicas  y de emergencia.',
      'clinic': 'Clínica',
      'clinic_desc': 'Escenarios médicos y frases de tratamiento.',
      'start_learning': 'Comenzar a aprender',

//wiki
      'wiki_info1': 'Wiki Turística de Indonesia',
      'wiki_info2': 'Explora destinos famosos en Indonesia y aprende frases útiles para tu viaje.',
      'wiki_info3': '¿Dónde estás? Selecciona tu destino.',
      'wiki_info4': 'Destino Turístico',
      'wiki_des1': 'Isla famosa por sus playas, templos y cultura vibrante.',
      'wiki_des2': 'Corazón cultural de Java y hogar del templo Borobudur.',
      'wiki_des3': 'Capital bulliciosa que combina cultura, negocios e historia.',
      'wiki_des4': 'Uno de los paraísos marinos más hermosos del mundo',
      'wiki_info5': 'Consejos Generales de Viaje en Indonesia',
      'wiki_info6': 'Consejos esenciales para todos los viajeros',
      'wiki_drop1': '• Aprende frases básicas en indonesio – los locales aprecian el esfuerzo',
      'wiki_drop2': '• Viste de manera modesta, especialmente al visitar sitios religiosos',
      'wiki_drop3': '• Lleva siempre billetes pequeños (Rupia) para transacciones locales',
      'wiki_drop4': '• Descarga mapas offline antes de viajar a zonas remotas',
      'wiki_drop5': '• Prueba la comida callejera local en puestos concurridos (alto movimiento = comida fresca)',
      'wiki_drop6': '• Negocia precios en mercados y con vendedores ambulantes',
      'wiki_drop7': '• Usa taxis oficiales o apps de transporte (Gojek, Grab)',
      'wiki_drop8': '• Guarda copias de documentos importantes por separado',
      'wiki_drop9': '• Contrata un seguro de viaje antes de tu viaje',
      'wiki_drop10': '• Respeta las costumbres locales y prácticas religiosas',
      'wiki_info7': 'Números de Emergencia en Indonesia',
      'wiki_info8': 'Guarda estos números importantes antes de viajar',
      'wiki_em1': 'Policía: 110',
      'wiki_em2': 'Ambulancia: 118',
      'wiki_em3': 'Bomberos: 113',

      // quiz screen
      'quiz_title': 'Cuestionario',
      'quiz_soal_progress': 'Pregunta {current} / {total}',
      'quiz_hint': 'Escribe o graba tu respuesta...',
      'quiz_ref_answer': 'Respuesta de referencia:',
      'quiz_similarity': 'Similitud:',
      'quiz_submit': 'Enviar Respuesta',
      'quiz_fill_first': 'Por favor, escribe tu respuesta primero.',
      'quiz_analyzing': 'Tu respuesta está siendo analizada...',
      'quiz_finished': '¡Cuestionario Terminado!',
      'quiz_final_score': 'Tu Puntuación Final:',
      'quiz_correct_count': '{correct} correctas de {total} preguntas',
      'quiz_score_saved': 'Tu puntuación se ha guardado automáticamente en tiempo real.',
      'quiz_back_menu': 'Volver al Menú',
      'quiz_status': 'Estado:',
      'quiz_reason_label': 'Razón:',
      'quiz_next': 'Siguiente Pregunta',
      'quiz_done': 'Terminar',
      'quiz_load_fail': 'Error al cargar preguntas. Inténtalo de nuevo.',
      'quiz_retry': 'Intentar de Nuevo',
      'quiz_no_questions': 'No hay preguntas disponibles.',
      'status_correct': 'Correcto',
      'status_partial': 'Casi Correcto',
      'status_incorrect': 'Incorrecto',
      'evaluated_by_gemini': 'Evaluado por Gemini',

      //Learning template
      'l_hint1' : '¡Escenario completado!',
      'l_hint2' : 'Terminaste todas las lecciones. ¿Listo para el cuestionario?',
      'l_completed': '{percent}% completado',
      'l_quiz_button': 'Iniciar cuestionario',
      'listening_top': 'Escucha el siguiente audio',
      'listening_sub': 'Presta atención y continúa con la siguiente pregunta',
      'writing_top': 'Escribe tu respuesta',
      'writing_sub': 'Traduce la siguiente oración al indonesio',
      'speaking_top': 'Habla en voz alta',
      'speaking_sub': 'Lee la oración claramente',
      'question_title': 'Pregunta {current} de {total}',
      'l_hint_writting' : 'Escribe tu respuesta en indonesio.',
      'l_send' : 'Enviar',
      'answer_empty': 'Por favor completa tu respuesta primero.',
      'answer_wrong': '❌ Respuesta incorrecta.\n\nConsejo: Intenta escribir "{correct}"',
      'answer_correct': '✅ ¡Correcto! Similitud: {score}%',
      'listening_status': 'Escuchando...',
      'mic_hint': 'Toca el micrófono y habla...',
      'send_voice': 'Enviar voz',
      'speaking_wrong': '❌ Incorrecto. Dijiste: "{spoken}".\n\nConsejo: Intenta decir "{correct}"',
      'all_done': '¡Todas las preguntas completadas!',
      'l_next' : 'Siguiente',
    },

    'ru': {
      // settings
      'settings_title': 'Настройки',
      'set_info': 'Управление настройками аккаунта',
      'profile_info': 'Информация профиля',
      'update_details': 'Обновите личные данные',
      'name': 'Имя',
      'email': 'Электронная почта',
      'email_cannot_change': 'Электронную почту нельзя изменить',
      'language_pref': 'Языковые настройки',
      'choose_language': 'Выберите язык',
      'recent_language': 'Текущий язык:',
      'save_changes': 'Сохранить изменения',
      'note_language_change': 'Примечание:\nСмена языка применится ко всем урокам.',

      // home screens
      'welcome_user': 'Добро пожаловать, {name}',
      'info_home_1': 'Общий прогресс',
      'quiz_info_1': 'Результаты тестов',
      'info_home_2': 'Начните своё путешествие',
      'info_home_3': 'Начните изучать индонезийский уже сегодня',
      'info_home_4': 'Выберите из 18 уроков в 3 уровнях сложности.',
      'info_home_5': 'Изучите важные фразы для аэропортов, отелей, ресторанов, покупок, транспорта и медицинских услуг.',
      'info_home_6': 'Транспорт и медицинские услуги.',
      'button_learn': 'Начать обучение',
      'info_home_7': 'Исследуйте Индонезию',
      'info_home_8': 'Популярные направления',
      'info_home_9': 'Советы путешественникам',
      'info_home_10': 'Экстренные фразы',
      'info_home_11': 'Открыть Wiki',

      // levels
      'level_info': 'Выберите уровень',
      'level_info_2': 'Выберите уровень сложности, чтобы начать',
      'lvl1': 'Начальный',
      'lvl1_sub': 'Базовый разговорный уровень',
      'lvl2': 'Средний',
      'lvl2_sub': 'Продвинутый разговорный уровень',
      'lvl3': 'Продвинутый',
      'lvl3_sub': 'Сложная коммуникация',
      'lvl_button': 'Начать обучение',

// scenario
      'airport': 'Аэропорт',
      'airport_desc': 'Изучите фразы и советы для аэропорта.',
      'hotel': 'Отель',
      'hotel_desc': 'Полезные фразы для проживания в отеле.',
      'restaurant': 'Ресторан',
      'restaurant_desc': 'Фразы и словарный запас для еды.',
      'shopping': 'Покупки',
      'shopping_desc': 'Слова и советы для покупок.',
      'market': 'Рынок',
      'market_desc': 'Основные фразы для традиционных рынков.',
      'transportation': 'Транспорт',
      'transportation_desc': 'Фразы для передвижения.',
      'hospital': 'Больница',
      'hospital_desc': 'Медицинские и экстренные фразы.',
      'clinic': 'Клиника',
      'clinic_desc': 'Медицинские сценарии и фразы для лечения.',
      'start_learning': 'Начать обучение',
//wiki
      'wiki_info1': 'Туристическая Википедия Индонезии',
      'wiki_info2': 'Исследуйте известные места Индонезии и выучите полезные фразы для поездки.',
      'wiki_info3': 'Где вы находитесь? Выберите место назначения.',
      'wiki_info4': 'Туристическое место',
      'wiki_des1': 'Остров, известный пляжами, храмами и живой культурой.',
      'wiki_des2': 'Культурное сердце Явы и дом храма Боробудур.',
      'wiki_des3': 'Шумная столица, сочетающая культуру, бизнес и историю.',
      'wiki_des4': 'Одна из самых красивых морских жемчужин в мире',
      'wiki_info5': 'Общие советы путешественникам по Индонезии',
      'wiki_info6': 'Важные советы для всех туристов',
      'wiki_drop1': '• Выучите базовые индонезийские фразы – местные оценят ваши усилия',
      'wiki_drop2': '• Одевайтесь скромно, особенно при посещении религиозных мест',
      'wiki_drop3': '• Всегда носите мелкие деньги (рупии) для местных транзакций',
      'wiki_drop4': '• Скачайте офлайн-карты перед поездкой в удаленные районы',
      'wiki_drop5': '• Попробуйте местную уличную еду в оживленных лавках (большой оборот = свежая еда)',
      'wiki_drop6': '• Торгуйтесь на рынках и с уличными продавцами',
      'wiki_drop7': '• Используйте официальное такси или приложения (Gojek, Grab)',
      'wiki_drop8': '• Храните копии важных документов отдельно',
      'wiki_drop9': '• Приобретите туристическую страховку до поездки',
      'wiki_drop10': '• Уважайте местные обычаи и религиозные практики',
      'wiki_info7': 'Экстренные номера в Индонезии',
      'wiki_info8': 'Сохраните эти номера перед поездкой',
      'wiki_em1': 'Полиция: 110',
      'wiki_em2': 'Скорая помощь: 118',
      'wiki_em3': 'Пожарная служба: 113',

      // quiz screen
      'quiz_title': 'Тест',
      'quiz_soal_progress': 'Вопрос {current} / {total}',
      'quiz_hint': 'Напишите или запишите ответ...',
      'quiz_ref_answer': 'Правильный ответ:',
      'quiz_similarity': 'Схожесть:',
      'quiz_submit': 'Отправить Ответ',
      'quiz_fill_first': 'Пожалуйста, сначала введите ответ.',
      'quiz_analyzing': 'Ваш ответ анализируется...',
      'quiz_finished': 'Тест Завершён!',
      'quiz_final_score': 'Ваш Итоговый Результат:',
      'quiz_correct_count': 'Правильно {correct} из {total} вопросов',
      'quiz_score_saved': 'Ваш результат автоматически сохранён в реальном времени.',
      'quiz_back_menu': 'Вернуться в Меню',
      'quiz_status': 'Статус:',
      'quiz_reason_label': 'Причина:',
      'quiz_next': 'Следующий Вопрос',
      'quiz_done': 'Завершить',
      'quiz_load_fail': 'Не удалось загрузить вопросы. Попробуйте снова.',
      'quiz_retry': 'Попробовать Снова',
      'quiz_no_questions': 'Вопросы недоступны.',
      'status_correct': 'Правильно',
      'status_partial': 'Почти правильно',
      'status_incorrect': 'Неправильно',
      'evaluated_by_gemini': 'Оценено Gemini',

      //Learning template
      'l_hint1' : 'Сценарий завершён!',
      'l_hint2' : 'Вы завершили все уроки. Готовы к тесту?',
      'l_completed': '{percent}% завершено',
      'l_quiz_button': 'Начать тест',
      'listening_top': 'Прослушайте следующую аудиозапись',
      'listening_sub': 'Слушайте внимательно и переходите к следующему вопросу',
      'writing_top': 'Напишите ваш ответ',
      'writing_sub': 'Переведите следующее предложение на индонезийский язык',
      'speaking_top': 'Произнесите вслух',
      'speaking_sub': 'Прочитайте предложение чётко',
      'question_title': 'Вопрос {current} из {total}',
      'l_hint_writting' : 'Введите ваш ответ на индонезийском языке.',
      'l_send' : 'Отправить',
      'answer_empty': 'Пожалуйста, сначала введите ваш ответ.',
      'answer_wrong': '❌ Неправильный ответ.\n\nПодсказка: Попробуйте написать "{correct}"',
      'answer_correct': '✅ Правильно! Сходство: {score}%',
      'listening_status': 'Прослушивание...',
      'mic_hint': 'Нажмите на микрофон и говорите...',
      'send_voice': 'Отправить голос',
      'speaking_wrong': '❌ Неправильно. Вы сказали: "{spoken}".\n\nПодсказка: Попробуйте сказать "{correct}"',
      'all_done': 'Все вопросы выполнены!',
      'l_next' : 'Далее',
    },

    'zh': {
      // settings
      'settings_title': '设置',
      'set_info': '管理您的账户偏好',
      'profile_info': '个人信息',
      'update_details': '更新您的个人信息',
      'name': '姓名',
      'email': '电子邮箱',
      'email_cannot_change': '电子邮箱无法更改',
      'language_pref': '语言偏好',
      'choose_language': '选择您的语言',
      'recent_language': '当前语言：',
      'save_changes': '保存更改',
      'note_language_change': '注意：\n更改语言将应用于所有课程。',

      // home screens
      'welcome_user': '欢迎，{name}',
      'info_home_1': '总体进度',
      'quiz_info_1': '测验表现',
      'info_home_2': '开始您的旅程',
      'info_home_3': '今天开始学习印尼语',
      'info_home_4': '从18节课程中选择，涵盖3个难度等级。',
      'info_home_5': '学习机场、酒店、餐厅、购物、交通和医疗场景中的常用短语。',
      'info_home_6': '交通和医疗相关内容。',
      'button_learn': '开始学习',
      'info_home_7': '探索印度尼西亚',
      'info_home_8': '热门目的地',
      'info_home_9': '旅行小贴士',
      'info_home_10': '紧急用语',
      'info_home_11': '探索百科',

      // levels
      'level_info': '选择你的级别',
      'level_info_2': '选择难度级别开始你的旅程',
      'lvl1': '初级',
      'lvl1_sub': '基础日常对话',
      'lvl2': '中级',
      'lvl2_sub': '进阶日常对话',
      'lvl3': '高级',
      'lvl3_sub': '复杂交流',
      'lvl_button': '开始学习',

// scenario
      'airport': '机场',
      'airport_desc': '学习机场常用短语和技巧。',
      'hotel': '酒店',
      'hotel_desc': '酒店住宿常用句子。',
      'restaurant': '餐厅',
      'restaurant_desc': '餐饮短语和词汇。',
      'shopping': '购物',
      'shopping_desc': '购物用词和技巧。',
      'market': '市场',
      'market_desc': '传统市场的基本短语。',
      'transportation': '交通',
      'transportation_desc': '出行常用短语。',
      'hospital': '医院',
      'hospital_desc': '医疗和紧急短语。',
      'clinic': '诊所',
      'clinic_desc': '医疗方案和治疗短语。',
      'start_learning': '开始学习',
//wiki
      'wiki_info1': '印度尼西亚旅游百科',
      'wiki_info2': '探索印度尼西亚的著名景点，并学习旅行中有用的短语。',
      'wiki_info3': '你在哪里？选择你的目的地。',
      'wiki_info4': '旅游目的地',
      'wiki_des1': '以海滩、寺庙和多彩文化闻名的岛屿。',
      'wiki_des2': '爪哇文化中心，婆罗浮屠寺的所在地。',
      'wiki_des3': '融合文化、商业和历史的繁忙首都。',
      'wiki_des4': '世界上最美丽的海洋天堂之一',
      'wiki_info5': '印尼旅行通用建议',
      'wiki_info6': '所有旅行者的重要提示',
      'wiki_drop1': '• 学习基础印尼语短语——当地人会欣赏你的努力',
      'wiki_drop2': '• 穿着得体，尤其是参观宗教场所时',
      'wiki_drop3': '• 始终携带小额纸币（卢比）进行当地交易',
      'wiki_drop4': '• 前往偏远地区前下载离线地图',
      'wiki_drop5': '• 尝试繁忙摊位的当地街头美食（周转快 = 食材新鲜）',
      'wiki_drop6': '• 在市场和街头小贩处讨价还价',
      'wiki_drop7': '• 使用官方出租车或叫车应用（Gojek, Grab）',
      'wiki_drop8': '• 将重要文件的副本单独保存',
      'wiki_drop9': '• 出行前购买旅游保险',
      'wiki_drop10': '• 尊重当地习俗和宗教实践',
      'wiki_info7': '印尼紧急号码',
      'wiki_info8': '旅行前保存这些重要号码',
      'wiki_em1': '警察: 110',
      'wiki_em2': '救护车: 118',
      'wiki_em3': '消防: 113',

      // quiz screen
      'quiz_title': '测验',
      'quiz_soal_progress': '第 {current} / {total} 题',
      'quiz_hint': '写下或录制您的答案...',
      'quiz_ref_answer': '参考答案：',
      'quiz_similarity': '相似度：',
      'quiz_submit': '提交答案',
      'quiz_fill_first': '请先填写您的答案。',
      'quiz_analyzing': '正在分析您的答案...',
      'quiz_finished': '测验完成！',
      'quiz_final_score': '您的最终得分：',
      'quiz_correct_count': '{total} 题中答对 {correct} 题',
      'quiz_score_saved': '您的成绩已实时自动保存。',
      'quiz_back_menu': '返回菜单',
      'quiz_status': '状态：',
      'quiz_reason_label': '原因：',
      'quiz_next': '下一题',
      'quiz_done': '完成',
      'quiz_load_fail': '加载题目失败，请重试。',
      'quiz_retry': '重试',
      'quiz_no_questions': '暂无题目。',
      'status_correct': '正确',
      'status_partial': '几乎正确',
      'status_incorrect': '错误',
      'evaluated_by_gemini': '由 Gemini 评估',

      //Learning template
      'l_hint1' : '场景已完成！',
      'l_hint2' : '你已完成所有课程，准备好参加测验了吗？',
      'l_completed': '{percent}% 已完成',
      'l_quiz_button': '开始测验',
      'listening_top': '请听以下音频',
      'listening_sub': '请仔细听，然后继续下一题',
      'writing_top': '写下你的答案',
      'writing_sub': '将以下句子翻译成印度尼西亚语',
      'speaking_top': '大声说出来',
      'speaking_sub': '请清晰地朗读这个句子',
      'question_title': '第 {current} 题，共 {total} 题',
      'l_hint_writting' : '请用印度尼西亚语输入你的答案。',
      'l_send' : '提交',
      'answer_empty': '请先填写你的答案。',
      'answer_wrong': '❌ 答案错误。\n\n提示：试着写 "{correct}"',
      'answer_correct': '✅ 正确！相似度：{score}%',
      'listening_status': '正在收听...',
      'mic_hint': '点击麦克风并说话...',
      'send_voice': '发送语音',
      'speaking_wrong': '❌ 错误。你说的是："{spoken}"。\n\n提示：试着说 "{correct}"',
      'all_done': '所有问题已完成！',
      'l_next' : '下一个',
    },
  };

  String t(String key, {Map<String, String>? params}) {
    String text = translations[_currentLang]?[key] ?? key;

    if (params != null) {
      params.forEach((k, v) {
        text = text.replaceAll('{$k}', v);
      });
    }

    return text;
  }

  Future<void> changeLanguage(String lang) async {
    _currentLang = lang;
    notifyListeners();

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('lang', lang);
  }

  Future<void> loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLang = prefs.getString('lang') ?? 'en';
  }
}